package fossils.fossils.init;

import fossils.fossils.FossilMod;
import fossils.fossils.common.entity.block.FossilSkeletonFifteenPieceBlockEntity;
import fossils.fossils.common.entity.block.FossilSkeletonFivePieceBlockEntity;
import fossils.fossils.common.entity.block.FossilSkeletonTenPieceBlockEntity;
import fossils.fossils.common.entity.block.FossilSkeletonTwentyPieceBlockEntity;
import fossils.fossils.common.entity.block.FossilSlabBlockEntity;
import net.minecraft.world.level.block.entity.BlockEntityType;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

public class FossilBlockEntities {
	public static final DeferredRegister<BlockEntityType<?>> REGISTER = DeferredRegister.create(ForgeRegistries.BLOCK_ENTITY_TYPES, FossilMod.MOD_ID);

    public static final RegistryObject<BlockEntityType<FossilSlabBlockEntity>> FOSSIL_SLAB = REGISTER.register("fossil_slab", () -> BlockEntityType.Builder.of(FossilSlabBlockEntity::new, FossilBlocks.TROPAEUM.get(), FossilBlocks.ALIENUM.get()).build(null));
    public static final RegistryObject<BlockEntityType<FossilSkeletonFivePieceBlockEntity>> FOSSIL_SKELETON_FIVE_PIECE = REGISTER.register("fossil_skeleton_five_piece", () -> BlockEntityType.Builder.of(FossilSkeletonFivePieceBlockEntity::new, FossilBlocks.EUNOTOSAURUS.get(), FossilBlocks.ACANTHOSTEGA.get(), FossilBlocks.STENOKRANIO.get(), FossilBlocks.HENODUS.get(), FossilBlocks.PROTOCERAS.get(), FossilBlocks.DIPLOCAULUSMAGNICORNIS.get(), FossilBlocks.TIKTAALIK.get(), FossilBlocks.SUMINIA.get(), FossilBlocks.MEGALANCOSAURUS.get(), FossilBlocks.RIOJASUCHUS.get(), FossilBlocks.DREPANOSAURUS.get(), FossilBlocks.MANIDENS.get(), FossilBlocks.DASYCEPS.get(), FossilBlocks.AQUILOPS.get(), FossilBlocks.BANNYKUS.get(), FossilBlocks.YUANYANGLONG.get(), FossilBlocks.MEI.get(), FossilBlocks.ANATOSUCHUS.get(), FossilBlocks.NQWEBASAURUS.get(), FossilBlocks.SHUVUUIA.get(), FossilBlocks.PELECANIMIMUS.get()).build(null));
    public static final RegistryObject<BlockEntityType<FossilSkeletonTenPieceBlockEntity>> FOSSIL_SKELETON_TEN_PIECE = REGISTER.register("fossil_skeleton_ten_piece", () -> BlockEntityType.Builder.of(FossilSkeletonTenPieceBlockEntity::new, FossilBlocks.NASUTOCERATOPS.get(), FossilBlocks.SYNTHETOCERAS.get(), FossilBlocks.DIMETRODONGRANDIS.get(), FossilBlocks.ENDOTHIODONBATHYSTOMA.get(), FossilBlocks.NIGERPETON.get(), FossilBlocks.PLACERIAS.get(), FossilBlocks.ARIZONASAURUS.get(), FossilBlocks.POPOSAURUS.get(), FossilBlocks.STAHLECKERIA.get(), FossilBlocks.STAGONOLEPIS.get(), FossilBlocks.GUANLONG.get(), FossilBlocks.ICHTHYOSAURUS.get(), FossilBlocks.SCELIDOSAURUS.get(), FossilBlocks.PIATNITZKYSAURUS.get(), FossilBlocks.DEARC.get(), FossilBlocks.TUPANDACTYLUSNAVIGANS.get(), FossilBlocks.SKORPIOVENATOR.get(), FossilBlocks.PROTOCERATOPSANDREWSI.get(), FossilBlocks.STRUTHIOMIMUS.get(), FossilBlocks.MONTANOCERATOPS.get(), FossilBlocks.KENTROSAURUS.get()).build(null));
    public static final RegistryObject<BlockEntityType<FossilSkeletonFifteenPieceBlockEntity>> FOSSIL_SKELETON_FIFTEEN_PIECE = REGISTER.register("fossil_skeleton_fifteen_piece", () -> BlockEntityType.Builder.of(FossilSkeletonFifteenPieceBlockEntity::new, FossilBlocks.BISONLATIFRONS.get(), FossilBlocks.SMILOSUCHUS.get(), FossilBlocks.CRYOLOPHOSAURUS.get(), FossilBlocks.DILOPHOSAURUS.get(), FossilBlocks.CERATOSAURUSDENTISULCATUS.get(), FossilBlocks.YINGSHANOSAURUS.get(), FossilBlocks.PATAGOSAURUS.get(), FossilBlocks.EOABELISAURUS.get(), FossilBlocks.CAMPTOSAURUS.get(), FossilBlocks.KOOLASUCHUS.get(), FossilBlocks.SAUROPELTA.get(), FossilBlocks.ABYSSOSAURUS.get(), FossilBlocks.MUTTABURRASAURUS.get(), FossilBlocks.DEINONYCHUS.get(), FossilBlocks.BRACHYTRACHELOPAN.get(), FossilBlocks.TETHYSHADROS.get(), FossilBlocks.REGALICERATOPS.get(), FossilBlocks.HUAXIAZHOULONG.get(), FossilBlocks.VELOCIRAPTOR.get(), FossilBlocks.WUERHOSAURUS.get()).build(null));
    public static final RegistryObject<BlockEntityType<FossilSkeletonTwentyPieceBlockEntity>> FOSSIL_SKELETON_TWENTY_PIECE = REGISTER.register("fossil_skeleton_twenty_piece", () -> BlockEntityType.Builder.of(FossilSkeletonTwentyPieceBlockEntity::new, FossilBlocks.SHONISAURUS.get(), FossilBlocks.APATOSAURUS.get(), FossilBlocks.BRACHIOSAURUS.get(), FossilBlocks.IGUANODON.get(), FossilBlocks.AMARGASAURUS.get(), FossilBlocks.NIGERSAURUS.get(), FossilBlocks.SARCOSUCHUS.get(), FossilBlocks.PLIOSAURUS.get(), FossilBlocks.HATZEGOPTERYX.get(), FossilBlocks.CARCHARODONTOSAURUS.get(), FossilBlocks.EDMONTOSAURUSANNECTENS.get(), FossilBlocks.TYRANNOSAURUS.get(), FossilBlocks.SPINOSAURUS.get(), FossilBlocks.UTAHRAPTOR.get()).build(null));
	
}
