package fossils.fossils.init;

import fossils.fossils.FossilMod;
import fossils.fossils.common.block.FossilSkeletonFifteenPieceBlock;
import fossils.fossils.common.block.FossilSkeletonFivePieceBlock;
import fossils.fossils.common.block.FossilSkeletonTenPieceBlock;
import fossils.fossils.common.block.FossilSkeletonTwentyPieceBlock;
import fossils.fossils.common.block.FossilSlabBlock;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.SoundType;
import net.minecraft.world.level.block.state.BlockBehaviour.Properties;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

public class FossilBlocks {
	public static final DeferredRegister<Block> REGISTER = DeferredRegister.create(ForgeRegistries.BLOCKS, FossilMod.MOD_ID);

	//Slabs
	public static final RegistryObject<FossilSlabBlock> TROPAEUM = REGISTER.register("tropaeum_fossil", () -> new FossilSlabBlock(FossilSlabBlock.Types.TROPAEUM, Properties.of().strength(2.0F, 3.0F).sound(SoundType.STONE).requiresCorrectToolForDrops().noCollission().noOcclusion()));
	public static final RegistryObject<FossilSlabBlock> ALIENUM = REGISTER.register("alienum_fossil", () -> new FossilSlabBlock(FossilSlabBlock.Types.ALIENUM, Properties.of().strength(2.0F, 3.0F).sound(SoundType.STONE).requiresCorrectToolForDrops().noCollission().noOcclusion()));
	
	//Five
	public static final RegistryObject<FossilSkeletonFivePieceBlock> EUNOTOSAURUS = REGISTER.register("eunotosaurus_fossil", () -> new FossilSkeletonFivePieceBlock(FossilSkeletonFivePieceBlock.Types.EUNOTOSAURUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFivePieceBlock> PELECANIMIMUS = REGISTER.register("pelecanimimus_fossil", () -> new FossilSkeletonFivePieceBlock(FossilSkeletonFivePieceBlock.Types.PELECANIMIMUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFivePieceBlock> ACANTHOSTEGA = REGISTER.register("acanthostega_fossil", () -> new FossilSkeletonFivePieceBlock(FossilSkeletonFivePieceBlock.Types.ACANTHOSTEGA, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFivePieceBlock> STENOKRANIO = REGISTER.register("stenokranio_fossil", () -> new FossilSkeletonFivePieceBlock(FossilSkeletonFivePieceBlock.Types.STENOKRANIO, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFivePieceBlock> HENODUS = REGISTER.register("henodus_fossil", () -> new FossilSkeletonFivePieceBlock(FossilSkeletonFivePieceBlock.Types.HENODUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFivePieceBlock> PROTOCERAS = REGISTER.register("protoceras_fossil", () -> new FossilSkeletonFivePieceBlock(FossilSkeletonFivePieceBlock.Types.PROTOCERAS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFivePieceBlock> DIPLOCAULUSMAGNICORNIS = REGISTER.register("diplocaulusmagnicornis_fossil", () -> new FossilSkeletonFivePieceBlock(FossilSkeletonFivePieceBlock.Types.DIPLOCAULUSMAGNICORNIS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFivePieceBlock> TIKTAALIK = REGISTER.register("tiktaalik_fossil", () -> new FossilSkeletonFivePieceBlock(FossilSkeletonFivePieceBlock.Types.TIKTAALIK, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFivePieceBlock> SUMINIA = REGISTER.register("suminia_fossil", () -> new FossilSkeletonFivePieceBlock(FossilSkeletonFivePieceBlock.Types.SUMINIA, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFivePieceBlock> MEGALANCOSAURUS = REGISTER.register("megalancosaurus_fossil", () -> new FossilSkeletonFivePieceBlock(FossilSkeletonFivePieceBlock.Types.MEGALANCOSAURUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFivePieceBlock> RIOJASUCHUS = REGISTER.register("riojasuchus_fossil", () -> new FossilSkeletonFivePieceBlock(FossilSkeletonFivePieceBlock.Types.RIOJASUCHUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFivePieceBlock> DREPANOSAURUS = REGISTER.register("drepanosaurus_fossil", () -> new FossilSkeletonFivePieceBlock(FossilSkeletonFivePieceBlock.Types.DREPANOSAURUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFivePieceBlock> MANIDENS = REGISTER.register("manidens_fossil", () -> new FossilSkeletonFivePieceBlock(FossilSkeletonFivePieceBlock.Types.MANIDENS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFivePieceBlock> DASYCEPS = REGISTER.register("dasyceps_fossil", () -> new FossilSkeletonFivePieceBlock(FossilSkeletonFivePieceBlock.Types.DASYCEPS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFivePieceBlock> AQUILOPS = REGISTER.register("aquilops_fossil", () -> new FossilSkeletonFivePieceBlock(FossilSkeletonFivePieceBlock.Types.AQUILOPS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFivePieceBlock> BANNYKUS = REGISTER.register("bannykus_fossil", () -> new FossilSkeletonFivePieceBlock(FossilSkeletonFivePieceBlock.Types.BANNYKUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFivePieceBlock> YUANYANGLONG = REGISTER.register("yuanyanglong_fossil", () -> new FossilSkeletonFivePieceBlock(FossilSkeletonFivePieceBlock.Types.YUANYANGLONG, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFivePieceBlock> MEI = REGISTER.register("mei_fossil", () -> new FossilSkeletonFivePieceBlock(FossilSkeletonFivePieceBlock.Types.MEI, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFivePieceBlock> ANATOSUCHUS = REGISTER.register("anatosuchus_fossil", () -> new FossilSkeletonFivePieceBlock(FossilSkeletonFivePieceBlock.Types.ANATOSUCHUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFivePieceBlock> NQWEBASAURUS = REGISTER.register("nqwebasaurus_fossil", () -> new FossilSkeletonFivePieceBlock(FossilSkeletonFivePieceBlock.Types.NQWEBASAURUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFivePieceBlock> SHUVUUIA = REGISTER.register("shuvuuia_fossil", () -> new FossilSkeletonFivePieceBlock(FossilSkeletonFivePieceBlock.Types.SHUVUUIA, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFivePieceBlock> SILESAURUS = REGISTER.register("silesaurus_fossil", () -> new FossilSkeletonFivePieceBlock(FossilSkeletonFivePieceBlock.Types.SILESAURUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFivePieceBlock> BUITRERAPTOR = REGISTER.register("buitreraptor_fossil", () -> new FossilSkeletonFivePieceBlock(FossilSkeletonFivePieceBlock.Types.BUITRERAPTOR, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFivePieceBlock> SYLVIORNIS = REGISTER.register("sylviornis_fossil", () -> new FossilSkeletonFivePieceBlock(FossilSkeletonFivePieceBlock.Types.SYLVIORNIS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFivePieceBlock> ANUROGNATHUS = REGISTER.register("anurognathus_fossil", () -> new FossilSkeletonFivePieceBlock(FossilSkeletonFivePieceBlock.Types.ANUROGNATHUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFivePieceBlock> COMPSOGNATHUS = REGISTER.register("compsognathus_fossil", () -> new FossilSkeletonFivePieceBlock(FossilSkeletonFivePieceBlock.Types.COMPSOGNATHUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFivePieceBlock> OKSOKO = REGISTER.register("oksoko_fossil", () -> new FossilSkeletonFivePieceBlock(FossilSkeletonFivePieceBlock.Types.OKSOKO, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFivePieceBlock> COLUMBA = REGISTER.register("columba_fossil", () -> new FossilSkeletonFivePieceBlock(FossilSkeletonFivePieceBlock.Types.COLUMBA, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFivePieceBlock> DIMORPHODON = REGISTER.register("dimorphodon_fossil", () -> new FossilSkeletonFivePieceBlock(FossilSkeletonFivePieceBlock.Types.DIMORPHODON, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFivePieceBlock> PTERODACTYLUS = REGISTER.register("pterodactylus_fossil", () -> new FossilSkeletonFivePieceBlock(FossilSkeletonFivePieceBlock.Types.PTERODACTYLUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFivePieceBlock> BOTHRIOLEPIS = REGISTER.register("bothriolepis_fossil", () -> new FossilSkeletonFivePieceBlock(FossilSkeletonFivePieceBlock.Types.BOTHRIOLEPIS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFivePieceBlock> PLATYHYSTRIX = REGISTER.register("platyhystrix_fossil", () -> new FossilSkeletonFivePieceBlock(FossilSkeletonFivePieceBlock.Types.PLATYHYSTRIX, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));


	//Ten
	public static final RegistryObject<FossilSkeletonTenPieceBlock> KENTROSAURUS = REGISTER.register("kentrosaurus_fossil", () -> new FossilSkeletonTenPieceBlock(FossilSkeletonTenPieceBlock.Types.KENTROSAURUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTenPieceBlock> NASUTOCERATOPS = REGISTER.register("nasutoceratops_fossil", () -> new FossilSkeletonTenPieceBlock(FossilSkeletonTenPieceBlock.Types.NASUTOCERATOPS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTenPieceBlock> SYNTHETOCERAS = REGISTER.register("synthetoceras_fossil", () -> new FossilSkeletonTenPieceBlock(FossilSkeletonTenPieceBlock.Types.SYNTHETOCERAS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTenPieceBlock> DIMETRODONGRANDIS = REGISTER.register("dimetrodongrandis_fossil", () -> new FossilSkeletonTenPieceBlock(FossilSkeletonTenPieceBlock.Types.DIMETRODONGRANDIS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTenPieceBlock> ENDOTHIODONBATHYSTOMA = REGISTER.register("endothiodonbathystoma_fossil", () -> new FossilSkeletonTenPieceBlock(FossilSkeletonTenPieceBlock.Types.ENDOTHIODONBATHYSTOMA, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTenPieceBlock> NIGERPETON = REGISTER.register("nigerpeton_fossil", () -> new FossilSkeletonTenPieceBlock(FossilSkeletonTenPieceBlock.Types.NIGERPETON, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTenPieceBlock> PLACERIAS = REGISTER.register("placerias_fossil", () -> new FossilSkeletonTenPieceBlock(FossilSkeletonTenPieceBlock.Types.PLACERIAS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTenPieceBlock> ARIZONASAURUS = REGISTER.register("arizonasaurus_fossil", () -> new FossilSkeletonTenPieceBlock(FossilSkeletonTenPieceBlock.Types.ARIZONASAURUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTenPieceBlock> POPOSAURUS = REGISTER.register("poposaurus_fossil", () -> new FossilSkeletonTenPieceBlock(FossilSkeletonTenPieceBlock.Types.POPOSAURUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTenPieceBlock> STAHLECKERIA = REGISTER.register("stahleckeria_fossil", () -> new FossilSkeletonTenPieceBlock(FossilSkeletonTenPieceBlock.Types.STAHLECKERIA, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTenPieceBlock> STAGONOLEPIS = REGISTER.register("stagonolepis_fossil", () -> new FossilSkeletonTenPieceBlock(FossilSkeletonTenPieceBlock.Types.STAGONOLEPIS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTenPieceBlock> GUANLONG = REGISTER.register("guanlong_fossil", () -> new FossilSkeletonTenPieceBlock(FossilSkeletonTenPieceBlock.Types.GUANLONG, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTenPieceBlock> ICHTHYOSAURUS = REGISTER.register("ichthyosaurus_fossil", () -> new FossilSkeletonTenPieceBlock(FossilSkeletonTenPieceBlock.Types.ICHTHYOSAURUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTenPieceBlock> SCELIDOSAURUS = REGISTER.register("scelidosaurus_fossil", () -> new FossilSkeletonTenPieceBlock(FossilSkeletonTenPieceBlock.Types.SCELIDOSAURUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTenPieceBlock> PIATNITZKYSAURUS = REGISTER.register("piatnitzkysaurus_fossil", () -> new FossilSkeletonTenPieceBlock(FossilSkeletonTenPieceBlock.Types.PIATNITZKYSAURUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTenPieceBlock> DEARC = REGISTER.register("dearc_fossil", () -> new FossilSkeletonTenPieceBlock(FossilSkeletonTenPieceBlock.Types.DEARC, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTenPieceBlock> TUPANDACTYLUSNAVIGANS = REGISTER.register("tupandactylusnavigans_fossil", () -> new FossilSkeletonTenPieceBlock(FossilSkeletonTenPieceBlock.Types.TUPANDACTYLUSNAVIGANS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTenPieceBlock> SKORPIOVENATOR = REGISTER.register("skorpiovenator_fossil", () -> new FossilSkeletonTenPieceBlock(FossilSkeletonTenPieceBlock.Types.SKORPIOVENATOR, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTenPieceBlock> PROTOCERATOPSANDREWSI = REGISTER.register("protoceratopsandrewsi_fossil", () -> new FossilSkeletonTenPieceBlock(FossilSkeletonTenPieceBlock.Types.PROTOCERATOPSANDREWSI, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTenPieceBlock> STRUTHIOMIMUS = REGISTER.register("struthiomimus_fossil", () -> new FossilSkeletonTenPieceBlock(FossilSkeletonTenPieceBlock.Types.STRUTHIOMIMUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTenPieceBlock> MONTANOCERATOPS = REGISTER.register("montanoceratops_fossil", () -> new FossilSkeletonTenPieceBlock(FossilSkeletonTenPieceBlock.Types.MONTANOCERATOPS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTenPieceBlock> DORUDON = REGISTER.register("dorudon_fossil", () -> new FossilSkeletonTenPieceBlock(FossilSkeletonTenPieceBlock.Types.DORUDON, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTenPieceBlock> GASTORNIS = REGISTER.register("gastornis_fossil", () -> new FossilSkeletonTenPieceBlock(FossilSkeletonTenPieceBlock.Types.GASTORNIS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTenPieceBlock> KUTCHICETUS = REGISTER.register("kutchicetus_fossil", () -> new FossilSkeletonTenPieceBlock(FossilSkeletonTenPieceBlock.Types.KUTCHICETUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTenPieceBlock> PRODINOCERAS = REGISTER.register("prodinoceras_fossil", () -> new FossilSkeletonTenPieceBlock(FossilSkeletonTenPieceBlock.Types.PRODINOCERAS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTenPieceBlock> THYLACOLEO = REGISTER.register("thylacoleo_fossil", () -> new FossilSkeletonTenPieceBlock(FossilSkeletonTenPieceBlock.Types.THYLACOLEO, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTenPieceBlock> SINCLAIROMERYX = REGISTER.register("sinclairomeryx_fossil", () -> new FossilSkeletonTenPieceBlock(FossilSkeletonTenPieceBlock.Types.SINCLAIROMERYX, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTenPieceBlock> DINOCROCUTA = REGISTER.register("dinocrocuta_fossil", () -> new FossilSkeletonTenPieceBlock(FossilSkeletonTenPieceBlock.Types.DINOCROCUTA, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTenPieceBlock> COELOPHYSIS = REGISTER.register("coelophysis_fossil", () -> new FossilSkeletonTenPieceBlock(FossilSkeletonTenPieceBlock.Types.COELOPHYSIS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTenPieceBlock> LITOCRANIUS = REGISTER.register("litocranius_fossil", () -> new FossilSkeletonTenPieceBlock(FossilSkeletonTenPieceBlock.Types.LITOCRANIUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTenPieceBlock> THEROPITHECUS = REGISTER.register("theropithecus_fossil", () -> new FossilSkeletonTenPieceBlock(FossilSkeletonTenPieceBlock.Types.THEROPITHECUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTenPieceBlock> DODO = REGISTER.register("dodo_fossil", () -> new FossilSkeletonTenPieceBlock(FossilSkeletonTenPieceBlock.Types.DODO, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTenPieceBlock> DIABLOCERATOPS = REGISTER.register("diabloceratops_fossil", () -> new FossilSkeletonTenPieceBlock(FossilSkeletonTenPieceBlock.Types.DIABLOCERATOPS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTenPieceBlock> MOSCHOPS = REGISTER.register("moschops_fossil", () -> new FossilSkeletonTenPieceBlock(FossilSkeletonTenPieceBlock.Types.MOSCHOPS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTenPieceBlock> BARYLAMBDA = REGISTER.register("barylambda_fossil", () -> new FossilSkeletonTenPieceBlock(FossilSkeletonTenPieceBlock.Types.BARYLAMBDA, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));


	//Fifteen
	public static final RegistryObject<FossilSkeletonFifteenPieceBlock> WUERHOSAURUS = REGISTER.register("wuerhosaurus_fossil", () -> new FossilSkeletonFifteenPieceBlock(FossilSkeletonFifteenPieceBlock.Types.WUERHOSAURUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFifteenPieceBlock> BISONLATIFRONS = REGISTER.register("bisonlatifrons_fossil", () -> new FossilSkeletonFifteenPieceBlock(FossilSkeletonFifteenPieceBlock.Types.BISONLATIFRONS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFifteenPieceBlock> SMILOSUCHUS = REGISTER.register("smilosuchus_fossil", () -> new FossilSkeletonFifteenPieceBlock(FossilSkeletonFifteenPieceBlock.Types.SMILOSUCHUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFifteenPieceBlock> CRYOLOPHOSAURUS = REGISTER.register("cryolophosaurus_fossil", () -> new FossilSkeletonFifteenPieceBlock(FossilSkeletonFifteenPieceBlock.Types.CRYOLOPHOSAURUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFifteenPieceBlock> DILOPHOSAURUS = REGISTER.register("dilophosaurus_fossil", () -> new FossilSkeletonFifteenPieceBlock(FossilSkeletonFifteenPieceBlock.Types.DILOPHOSAURUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFifteenPieceBlock> CERATOSAURUSDENTISULCATUS = REGISTER.register("ceratosaurusdentisulcatus_fossil", () -> new FossilSkeletonFifteenPieceBlock(FossilSkeletonFifteenPieceBlock.Types.CERATOSAURUSDENTISULCATUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFifteenPieceBlock> YINGSHANOSAURUS = REGISTER.register("yingshanosaurus_fossil", () -> new FossilSkeletonFifteenPieceBlock(FossilSkeletonFifteenPieceBlock.Types.YINGSHANOSAURUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFifteenPieceBlock> PATAGOSAURUS = REGISTER.register("patagosaurus_fossil", () -> new FossilSkeletonFifteenPieceBlock(FossilSkeletonFifteenPieceBlock.Types.PATAGOSAURUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFifteenPieceBlock> EOABELISAURUS = REGISTER.register("eoabelisaurus_fossil", () -> new FossilSkeletonFifteenPieceBlock(FossilSkeletonFifteenPieceBlock.Types.EOABELISAURUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFifteenPieceBlock> CAMPTOSAURUS = REGISTER.register("camptosaurus_fossil", () -> new FossilSkeletonFifteenPieceBlock(FossilSkeletonFifteenPieceBlock.Types.CAMPTOSAURUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFifteenPieceBlock> KOOLASUCHUS = REGISTER.register("koolasuchus_fossil", () -> new FossilSkeletonFifteenPieceBlock(FossilSkeletonFifteenPieceBlock.Types.KOOLASUCHUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFifteenPieceBlock> SAUROPELTA = REGISTER.register("sauropelta_fossil", () -> new FossilSkeletonFifteenPieceBlock(FossilSkeletonFifteenPieceBlock.Types.SAUROPELTA, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFifteenPieceBlock> ABYSSOSAURUS = REGISTER.register("abyssosaurus_fossil", () -> new FossilSkeletonFifteenPieceBlock(FossilSkeletonFifteenPieceBlock.Types.ABYSSOSAURUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFifteenPieceBlock> MUTTABURRASAURUS = REGISTER.register("muttaburrasaurus_fossil", () -> new FossilSkeletonFifteenPieceBlock(FossilSkeletonFifteenPieceBlock.Types.MUTTABURRASAURUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFifteenPieceBlock> DEINONYCHUS = REGISTER.register("deinonychus_fossil", () -> new FossilSkeletonFifteenPieceBlock(FossilSkeletonFifteenPieceBlock.Types.DEINONYCHUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFifteenPieceBlock> BRACHYTRACHELOPAN = REGISTER.register("brachytrachelopan_fossil", () -> new FossilSkeletonFifteenPieceBlock(FossilSkeletonFifteenPieceBlock.Types.BRACHYTRACHELOPAN, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFifteenPieceBlock> TETHYSHADROS = REGISTER.register("tethyshadros_fossil", () -> new FossilSkeletonFifteenPieceBlock(FossilSkeletonFifteenPieceBlock.Types.TETHYSHADROS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFifteenPieceBlock> REGALICERATOPS = REGISTER.register("regaliceratops_fossil", () -> new FossilSkeletonFifteenPieceBlock(FossilSkeletonFifteenPieceBlock.Types.REGALICERATOPS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFifteenPieceBlock> HUAXIAZHOULONG = REGISTER.register("huaxiazhoulong_fossil", () -> new FossilSkeletonFifteenPieceBlock(FossilSkeletonFifteenPieceBlock.Types.HUAXIAZHOULONG, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFifteenPieceBlock> VELOCIRAPTOR = REGISTER.register("velociraptor_fossil", () -> new FossilSkeletonFifteenPieceBlock(FossilSkeletonFifteenPieceBlock.Types.VELOCIRAPTOR, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFifteenPieceBlock> KUBANOCHOERUS = REGISTER.register("kubanochoerus_fossil", () -> new FossilSkeletonFifteenPieceBlock(FossilSkeletonFifteenPieceBlock.Types.KUBANOCHOERUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFifteenPieceBlock> DECENNATHERIUM = REGISTER.register("decennatherium_fossil", () -> new FossilSkeletonFifteenPieceBlock(FossilSkeletonFifteenPieceBlock.Types.DECENNATHERIUM, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFifteenPieceBlock> PLATECARPUS = REGISTER.register("platecarpus_fossil", () -> new FossilSkeletonFifteenPieceBlock(FossilSkeletonFifteenPieceBlock.Types.PLATECARPUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFifteenPieceBlock> OVIRAPTOR = REGISTER.register("oviraptor_fossil", () -> new FossilSkeletonFifteenPieceBlock(FossilSkeletonFifteenPieceBlock.Types.OVIRAPTOR, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFifteenPieceBlock> RAJASAURUS = REGISTER.register("rajasaurus_fossil", () -> new FossilSkeletonFifteenPieceBlock(FossilSkeletonFifteenPieceBlock.Types.RAJASAURUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFifteenPieceBlock> ZARAFASAURA = REGISTER.register("zarafasaura_fossil", () -> new FossilSkeletonFifteenPieceBlock(FossilSkeletonFifteenPieceBlock.Types.ZARAFASAURA, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFifteenPieceBlock> TANYSTROPHEUS = REGISTER.register("tanystropheus_fossil", () -> new FossilSkeletonFifteenPieceBlock(FossilSkeletonFifteenPieceBlock.Types.TANYSTROPHEUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFifteenPieceBlock> INOSTRANCEVIA = REGISTER.register("inostrancevia_fossil", () -> new FossilSkeletonFifteenPieceBlock(FossilSkeletonFifteenPieceBlock.Types.INOSTRANCEVIA, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFifteenPieceBlock> OURANOSAURUS = REGISTER.register("ouranosaurus_fossil", () -> new FossilSkeletonFifteenPieceBlock(FossilSkeletonFifteenPieceBlock.Types.OURANOSAURUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFifteenPieceBlock> PYROTHERIUM = REGISTER.register("pyrotherium_fossil", () -> new FossilSkeletonFifteenPieceBlock(FossilSkeletonFifteenPieceBlock.Types.PYROTHERIUM, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonFifteenPieceBlock> MONOLOPHOSAURUS = REGISTER.register("monolophosaurus_fossil", () -> new FossilSkeletonFifteenPieceBlock(FossilSkeletonFifteenPieceBlock.Types.MONOLOPHOSAURUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	
	//Twenty
	public static final RegistryObject<FossilSkeletonTwentyPieceBlock> UTAHRAPTOR = REGISTER.register("utahraptor_fossil", () -> new FossilSkeletonTwentyPieceBlock(FossilSkeletonTwentyPieceBlock.Types.UTAHRAPTOR, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTwentyPieceBlock> SHONISAURUS = REGISTER.register("shonisaurus_fossil", () -> new FossilSkeletonTwentyPieceBlock(FossilSkeletonTwentyPieceBlock.Types.SHONISAURUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTwentyPieceBlock> APATOSAURUS = REGISTER.register("apatosaurus_fossil", () -> new FossilSkeletonTwentyPieceBlock(FossilSkeletonTwentyPieceBlock.Types.APATOSAURUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTwentyPieceBlock> BRACHIOSAURUS = REGISTER.register("brachiosaurus_fossil", () -> new FossilSkeletonTwentyPieceBlock(FossilSkeletonTwentyPieceBlock.Types.BRACHIOSAURUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTwentyPieceBlock> IGUANODON = REGISTER.register("iguanodon_fossil", () -> new FossilSkeletonTwentyPieceBlock(FossilSkeletonTwentyPieceBlock.Types.IGUANODON, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTwentyPieceBlock> AMARGASAURUS = REGISTER.register("amargasaurus_fossil", () -> new FossilSkeletonTwentyPieceBlock(FossilSkeletonTwentyPieceBlock.Types.AMARGASAURUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTwentyPieceBlock> NIGERSAURUS = REGISTER.register("nigersaurus_fossil", () -> new FossilSkeletonTwentyPieceBlock(FossilSkeletonTwentyPieceBlock.Types.NIGERSAURUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTwentyPieceBlock> SARCOSUCHUS = REGISTER.register("sarcosuchus_fossil", () -> new FossilSkeletonTwentyPieceBlock(FossilSkeletonTwentyPieceBlock.Types.SARCOSUCHUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTwentyPieceBlock> PLIOSAURUS = REGISTER.register("pliosaurus_fossil", () -> new FossilSkeletonTwentyPieceBlock(FossilSkeletonTwentyPieceBlock.Types.PLIOSAURUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTwentyPieceBlock> HATZEGOPTERYX = REGISTER.register("hatzegopteryx_fossil", () -> new FossilSkeletonTwentyPieceBlock(FossilSkeletonTwentyPieceBlock.Types.HATZEGOPTERYX, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTwentyPieceBlock> CARCHARODONTOSAURUS = REGISTER.register("carcharodontosaurus_fossil", () -> new FossilSkeletonTwentyPieceBlock(FossilSkeletonTwentyPieceBlock.Types.CARCHARODONTOSAURUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTwentyPieceBlock> EDMONTOSAURUSANNECTENS = REGISTER.register("edmontosaurusannectens_fossil", () -> new FossilSkeletonTwentyPieceBlock(FossilSkeletonTwentyPieceBlock.Types.EDMONTOSAURUSANNECTENS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTwentyPieceBlock> TYRANNOSAURUS = REGISTER.register("tyrannosaurus_fossil", () -> new FossilSkeletonTwentyPieceBlock(FossilSkeletonTwentyPieceBlock.Types.TYRANNOSAURUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTwentyPieceBlock> SPINOSAURUS = REGISTER.register("spinosaurus_fossil", () -> new FossilSkeletonTwentyPieceBlock(FossilSkeletonTwentyPieceBlock.Types.SPINOSAURUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTwentyPieceBlock> MEGACEROPS = REGISTER.register("megacerops_fossil", () -> new FossilSkeletonTwentyPieceBlock(FossilSkeletonTwentyPieceBlock.Types.MEGACEROPS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTwentyPieceBlock> EREMOTHERIUM = REGISTER.register("eremotherium_fossil", () -> new FossilSkeletonTwentyPieceBlock(FossilSkeletonTwentyPieceBlock.Types.EREMOTHERIUM, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTwentyPieceBlock> PANTHERATIGRIS = REGISTER.register("pantheratigris_fossil", () -> new FossilSkeletonTwentyPieceBlock(FossilSkeletonTwentyPieceBlock.Types.PANTHERATIGRIS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTwentyPieceBlock> COTYLORHYNCHUS = REGISTER.register("cotylorhynchus_fossil", () -> new FossilSkeletonTwentyPieceBlock(FossilSkeletonTwentyPieceBlock.Types.COTYLORHYNCHUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTwentyPieceBlock> ALLOSAURUS = REGISTER.register("allosaurus_fossil", () -> new FossilSkeletonTwentyPieceBlock(FossilSkeletonTwentyPieceBlock.Types.ALLOSAURUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTwentyPieceBlock> LIVYATAN = REGISTER.register("livyatan_fossil", () -> new FossilSkeletonTwentyPieceBlock(FossilSkeletonTwentyPieceBlock.Types.LIVYATAN, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTwentyPieceBlock> THERIZINOSAURUS = REGISTER.register("therizinosaurus_fossil", () -> new FossilSkeletonTwentyPieceBlock(FossilSkeletonTwentyPieceBlock.Types.THERIZINOSAURUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTwentyPieceBlock> ARISTONECTES = REGISTER.register("aristonectes_fossil", () -> new FossilSkeletonTwentyPieceBlock(FossilSkeletonTwentyPieceBlock.Types.ARISTONECTES, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTwentyPieceBlock> STEGOSAURUS = REGISTER.register("stegosaurus_fossil", () -> new FossilSkeletonTwentyPieceBlock(FossilSkeletonTwentyPieceBlock.Types.STEGOSAURUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTwentyPieceBlock> PARASAUROLOPHUSWALKERI = REGISTER.register("parasaurolophuswalkeri_fossil", () -> new FossilSkeletonTwentyPieceBlock(FossilSkeletonTwentyPieceBlock.Types.PARASAUROLOPHUSWALKERI, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTwentyPieceBlock> ARCHELON = REGISTER.register("archelon_fossil", () -> new FossilSkeletonTwentyPieceBlock(FossilSkeletonTwentyPieceBlock.Types.ARCHELON, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTwentyPieceBlock> DEINOTHERIUM = REGISTER.register("deinotherium_fossil", () -> new FossilSkeletonTwentyPieceBlock(FossilSkeletonTwentyPieceBlock.Types.DEINOTHERIUM, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTwentyPieceBlock> ANTEOSAURUS = REGISTER.register("anteosaurus_fossil", () -> new FossilSkeletonTwentyPieceBlock(FossilSkeletonTwentyPieceBlock.Types.ANTEOSAURUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));
	public static final RegistryObject<FossilSkeletonTwentyPieceBlock> DOEDICURUS = REGISTER.register("doedicurus_fossil", () -> new FossilSkeletonTwentyPieceBlock(FossilSkeletonTwentyPieceBlock.Types.DOEDICURUS, Properties.of().strength(2.0F, 3.0F).sound(SoundType.BONE_BLOCK).requiresCorrectToolForDrops().noOcclusion().noCollission()));

	public static final RegistryObject<Block> PRECAMBRIAN_FOSSIL_ORE = REGISTER.register("precambrian_fossil_ore", () -> new Block(Properties.copy(Blocks.STONE)));
	public static final RegistryObject<Block> CAMBRIAN_FOSSIL_ORE = REGISTER.register("cambrian_fossil_ore", () -> new Block(Properties.copy(Blocks.STONE)));
	public static final RegistryObject<Block> ORDOVICIAN_FOSSIL_ORE = REGISTER.register("ordovician_fossil_ore", () -> new Block(Properties.copy(Blocks.STONE)));
	public static final RegistryObject<Block> SILURIAN_FOSSIL_ORE = REGISTER.register("silurian_fossil_ore", () -> new Block(Properties.copy(Blocks.STONE)));
	public static final RegistryObject<Block> DEVONIAN_FOSSIL_ORE = REGISTER.register("devonian_fossil_ore", () -> new Block(Properties.copy(Blocks.STONE)));
	public static final RegistryObject<Block> CARBONIFEROUS_FOSSIL_ORE = REGISTER.register("carboniferous_fossil_ore", () -> new Block(Properties.copy(Blocks.STONE)));
	public static final RegistryObject<Block> PERMIAN_FOSSIL_ORE = REGISTER.register("permian_fossil_ore", () -> new Block(Properties.copy(Blocks.STONE)));
	public static final RegistryObject<Block> PERMIAN_DEEPSLATE_FOSSIL_ORE = REGISTER.register("permian_deepslate_fossil_ore", () -> new Block(Properties.copy(Blocks.STONE)));
	public static final RegistryObject<Block> TRIASSIC_FOSSIL_ORE = REGISTER.register("triassic_fossil_ore", () -> new Block(Properties.copy(Blocks.STONE)));
	public static final RegistryObject<Block> TRIASSIC_DEEPSLATE_FOSSIL_ORE = REGISTER.register("triassic_deepslate_fossil_ore", () -> new Block(Properties.copy(Blocks.STONE)));
	public static final RegistryObject<Block> JURASSIC_FOSSIL_ORE = REGISTER.register("jurassic_fossil_ore", () -> new Block(Properties.copy(Blocks.STONE)));
	public static final RegistryObject<Block> EARLY_CRETACEOUS_FOSSIL_ORE = REGISTER.register("early_cretaceous_fossil_ore", () -> new Block(Properties.copy(Blocks.STONE)));
	public static final RegistryObject<Block> LATE_CRETACEOUS_FOSSIL_ORE = REGISTER.register("late_cretaceous_fossil_ore", () -> new Block(Properties.copy(Blocks.STONE)));
	public static final RegistryObject<Block> PALEOGENE_FOSSIL_ORE = REGISTER.register("paleogene_fossil_ore", () -> new Block(Properties.copy(Blocks.STONE)));
	public static final RegistryObject<Block> NEOGENE_FOSSIL_ORE = REGISTER.register("neogene_fossil_ore", () -> new Block(Properties.copy(Blocks.STONE)));
	public static final RegistryObject<Block> QUATERNARY_FOSSIL_ORE = REGISTER.register("quaternary_fossil_ore", () -> new Block(Properties.copy(Blocks.STONE)));

	
}
