package fossils.fossils.client;

import fossils.fossils.FossilMod;
import fossils.fossils.client.blockentity.model.AlienumFossilSlabModel;
import fossils.fossils.client.blockentity.model.TropaeumFossilSlabModel;
import fossils.fossils.client.blockentity.model.acanthostega.AcanthostegaFossilFrameModel;
import fossils.fossils.client.blockentity.model.acanthostega.AcanthostegaFossilModel;
import fossils.fossils.client.blockentity.model.arizonasaurus.ArizonasaurusFossilFrameModel;
import fossils.fossils.client.blockentity.model.arizonasaurus.ArizonasaurusFossilModel;
import fossils.fossils.client.blockentity.model.bisonlatifrons.BisonlatifronsFossilFrameModel;
import fossils.fossils.client.blockentity.model.bisonlatifrons.BisonlatifronsFossilModel;
import fossils.fossils.client.blockentity.model.dimetrodongrandis.DimetrodonFossilFrameModel;
import fossils.fossils.client.blockentity.model.dimetrodongrandis.DimetrodonFossilModel;
import fossils.fossils.client.blockentity.model.diplocaulusmagnicornis.DiplocaulusmagnicornisFossilFrameModel;
import fossils.fossils.client.blockentity.model.diplocaulusmagnicornis.DiplocaulusmagnicornisFossilModel;
import fossils.fossils.client.blockentity.model.drepanosaurus.DrepanosaurusFossilFrameModel;
import fossils.fossils.client.blockentity.model.drepanosaurus.DrepanosaurusFossilModel;
import fossils.fossils.client.blockentity.model.endothiodonbathystoma.EndothiodonbathystomaFossilFrameModel;
import fossils.fossils.client.blockentity.model.endothiodonbathystoma.EndothiodonbathystomaFossilModel;
import fossils.fossils.client.blockentity.model.eunotosaurus.EunotosaurusFossilFrameModel;
import fossils.fossils.client.blockentity.model.eunotosaurus.EunotosaurusFossilModel;
import fossils.fossils.client.blockentity.model.guanlong.GuanlongFossilFrameModel;
import fossils.fossils.client.blockentity.model.guanlong.GuanlongFossilModel;
import fossils.fossils.client.blockentity.model.henodus.HenodusFossilFrameModel;
import fossils.fossils.client.blockentity.model.henodus.HenodusFossilModel;
import fossils.fossils.client.blockentity.model.ichthyosaurus.IchthyosaurusFossilFrameModel;
import fossils.fossils.client.blockentity.model.ichthyosaurus.IchthyosaurusFossilModel;
import fossils.fossils.client.blockentity.model.kentrosaurus.KentrosaurusFossilFrameModel;
import fossils.fossils.client.blockentity.model.kentrosaurus.KentrosaurusFossilModel;
import fossils.fossils.client.blockentity.model.manidens.ManidensFossilFrameModel;
import fossils.fossils.client.blockentity.model.manidens.ManidensFossilModel;
import fossils.fossils.client.blockentity.model.megalancosaurus.MegalancosaurusFossilFrameModel;
import fossils.fossils.client.blockentity.model.megalancosaurus.MegalancosaurusFossilModel;
import fossils.fossils.client.blockentity.model.nasutoceratops.NasutoceratopsFossilFrameModel;
import fossils.fossils.client.blockentity.model.nasutoceratops.NasutoceratopsFossilModel;
import fossils.fossils.client.blockentity.model.nigerpeton.NigerpetonFossilFrameModel;
import fossils.fossils.client.blockentity.model.nigerpeton.NigerpetonFossilModel;
import fossils.fossils.client.blockentity.model.pelecanimimus.PelecanimimusFossilFrameModel;
import fossils.fossils.client.blockentity.model.pelecanimimus.PelecanimimusFossilModel;
import fossils.fossils.client.blockentity.model.placerias.PlaceriasFossilFrameModel;
import fossils.fossils.client.blockentity.model.placerias.PlaceriasFossilModel;
import fossils.fossils.client.blockentity.model.poposaurus.PoposaurusFossilFrameModel;
import fossils.fossils.client.blockentity.model.poposaurus.PoposaurusFossilModel;
import fossils.fossils.client.blockentity.model.protoceras.ProtocerasFossilFrameModel;
import fossils.fossils.client.blockentity.model.protoceras.ProtocerasFossilModel;
import fossils.fossils.client.blockentity.model.riojasuchus.RiojasuchusFossilFrameModel;
import fossils.fossils.client.blockentity.model.riojasuchus.RiojasuchusFossilModel;
import fossils.fossils.client.blockentity.model.scelidosaurus.ScelidosaurusFossilFrameModel;
import fossils.fossils.client.blockentity.model.scelidosaurus.ScelidosaurusFossilModel;
import fossils.fossils.client.blockentity.model.shonisaurus.ShonisaurusFossilFrameModel;
import fossils.fossils.client.blockentity.model.shonisaurus.ShonisaurusFossilModel;
import fossils.fossils.client.blockentity.model.smilosuchus.SmilosuchusFossilFrameModel;
import fossils.fossils.client.blockentity.model.smilosuchus.SmilosuchusFossilModel;
import fossils.fossils.client.blockentity.model.stagonolepis.StagonolepisFossilFrameModel;
import fossils.fossils.client.blockentity.model.stagonolepis.StagonolepisFossilModel;
import fossils.fossils.client.blockentity.model.stahleckeria.StahleckeriaFossilFrameModel;
import fossils.fossils.client.blockentity.model.stahleckeria.StahleckeriaFossilModel;
import fossils.fossils.client.blockentity.model.stenokranio.StenokranioFossilFrameModel;
import fossils.fossils.client.blockentity.model.stenokranio.StenokranioFossilModel;
import fossils.fossils.client.blockentity.model.suminia.SuminiaFossilFrameModel;
import fossils.fossils.client.blockentity.model.suminia.SuminiaFossilModel;
import fossils.fossils.client.blockentity.model.synthetoceras.SynthetocerasFossilFrameModel;
import fossils.fossils.client.blockentity.model.synthetoceras.SynthetocerasFossilModel;
import fossils.fossils.client.blockentity.model.tiktaalik.TiktaalikFossilFrameModel;
import fossils.fossils.client.blockentity.model.tiktaalik.TiktaalikFossilModel;
import fossils.fossils.client.blockentity.model.utahraptor.UtahraptorFossilFrameModel;
import fossils.fossils.client.blockentity.model.utahraptor.UtahraptorFossilModel;
import fossils.fossils.client.blockentity.model.wuerhosaurus.WuerhosaurusFossilFrameModel;
import fossils.fossils.client.blockentity.model.wuerhosaurus.WuerhosaurusFossilModel;
import fossils.fossils.client.blockentity.render.FossilSkeletonFifteenPieceRenderer;
import fossils.fossils.client.blockentity.render.FossilSkeletonFivePieceRenderer;
import fossils.fossils.client.blockentity.render.FossilSkeletonTenPieceRenderer;
import fossils.fossils.client.blockentity.render.FossilSkeletonTwentyPieceRenderer;
import fossils.fossils.client.blockentity.render.FossilSlabRenderer;
import fossils.fossils.init.FossilBlockEntities;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.resources.ResourceLocation;
import net.minecraftforge.api.distmarker.Dist;
import net.minecraftforge.api.distmarker.OnlyIn;
import net.minecraftforge.client.event.EntityRenderersEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;

@OnlyIn(Dist.CLIENT)
@Mod.EventBusSubscriber(modid = FossilMod.MOD_ID, bus = Mod.EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)
public class ClientEvents {

	@SubscribeEvent
	public static void registerEntityRenders(EntityRenderersEvent.RegisterRenderers event) {
		event.registerBlockEntityRenderer(FossilBlockEntities.FOSSIL_SLAB.get(), FossilSlabRenderer::new);
		event.registerBlockEntityRenderer(FossilBlockEntities.FOSSIL_SKELETON_FIVE_PIECE.get(), FossilSkeletonFivePieceRenderer::new);
		event.registerBlockEntityRenderer(FossilBlockEntities.FOSSIL_SKELETON_TEN_PIECE.get(), FossilSkeletonTenPieceRenderer::new);
		event.registerBlockEntityRenderer(FossilBlockEntities.FOSSIL_SKELETON_FIFTEEN_PIECE.get(), FossilSkeletonFifteenPieceRenderer::new);
		event.registerBlockEntityRenderer(FossilBlockEntities.FOSSIL_SKELETON_TWENTY_PIECE.get(), FossilSkeletonTwentyPieceRenderer::new);
	}

	public static ModelLayerLocation TROPAEUM = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "tropaeum"), "tropaeum");
	public static ModelLayerLocation ALIENUM = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "alienum"), "alienum");
	public static ModelLayerLocation EUNOTOSAURUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "eunotosaurus"), "eunotosaurus");
	public static ModelLayerLocation EUNOTOSAURUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "eunotosaurus_frame"), "eunotosaurus_frame");
	public static ModelLayerLocation PELECANIMIMUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "pelecanimimus"), "pelecanimimus");
	public static ModelLayerLocation PELECANIMIMUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "pelecanimimus_frame"), "pelecanimimus_frame");
	public static ModelLayerLocation STENOKRANIO = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "stenokranio"), "stenokranio");
	public static ModelLayerLocation STENOKRANIO_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "stenokranio_frame"), "stenokranio_frame");
	public static ModelLayerLocation HENODUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "henodus"), "henodus");
	public static ModelLayerLocation HENODUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "henodus_frame"), "henodus_frame");
	public static ModelLayerLocation ACANTHOSTEGA = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "acanthostega"), "acanthostega");
	public static ModelLayerLocation ACANTHOSTEGA_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "acanthostega_frame"), "acanthostega_frame");
	public static ModelLayerLocation PROTOCERAS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "protoceras"), "protoceras");
	public static ModelLayerLocation PROTOCERAS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "protoceras_frame"), "protoceras_frame");
	public static ModelLayerLocation DIPLOCAULUSMAGNICORNIS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "diplocaulusmagnicornis"), "diplocaulusmagnicornis");
	public static ModelLayerLocation DIPLOCAULUSMAGNICORNIS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "diplocaulusmagnicornis_frame"), "diplocaulusmagnicornis_frame");
	public static ModelLayerLocation TIKTAALIK = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "tiktaalik"), "tiktaalik");
	public static ModelLayerLocation TIKTAALIK_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "tiktaalik_frame"), "tiktaalik_frame");
	public static ModelLayerLocation SUMINIA = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "suminia"), "suminia");
	public static ModelLayerLocation SUMINIA_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "suminia_frame"), "suminia_frame");
	public static ModelLayerLocation MEGALANCOSAURUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "megalancosaurus"), "megalancosaurus");
	public static ModelLayerLocation MEGALANCOSAURUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "megalancosaurus_frame"), "megalancosaurus_frame");
	public static ModelLayerLocation RIOJASUCHUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "riojasuchus"), "riojasuchus");
	public static ModelLayerLocation RIOJASUCHUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "riojasuchus_frame"), "riojasuchus_frame");
	public static ModelLayerLocation DREPANOSAURUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "drepanosaurus"), "drepanosaurus");
	public static ModelLayerLocation DREPANOSAURUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "drepanosaurus_frame"), "drepanosaurus_frame");
	public static ModelLayerLocation MANIDENS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "manidens"), "manidens");
	public static ModelLayerLocation MANIDENS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "manidens_frame"), "manidens_frame");
	public static ModelLayerLocation KENTROSAURUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "kentrosaurus"), "kentrosaurus");
	public static ModelLayerLocation KENTROSAURUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "kentrosaurus_frame"), "kentrosaurus_frame");
	public static ModelLayerLocation NASUTOCERATOPS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "nasutoceratops"), "nasutoceratops");
	public static ModelLayerLocation NASUTOCERATOPS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "nasutoceratops_frame"), "nasutoceratops_frame");
	public static ModelLayerLocation SYNTHETOCERAS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "synthetoceras"), "synthetoceras");
	public static ModelLayerLocation SYNTHETOCERAS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "synthetoceras_frame"), "synthetoceras_frame");
	public static ModelLayerLocation DIMETRODONGRANDIS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "dimetrodongrandis"), "dimetrodongrandis");
	public static ModelLayerLocation DIMETRODONGRANDIS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "dimetrodongrandis_frame"), "dimetrodongrandis_frame");
	public static ModelLayerLocation PLACERIAS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "placerias"), "placerias");
	public static ModelLayerLocation PLACERIAS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "placerias_frame"), "placerias_frame");
	public static ModelLayerLocation ENDOTHIODONBATHYSTOMA = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "endothiodonbathystoma"), "endothiodonbathystoma");
	public static ModelLayerLocation ENDOTHIODONBATHYSTOMA_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "endothiodonbathystoma_frame"), "endothiodonbathystoma_frame");
	public static ModelLayerLocation NIGERPETON = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "nigerpeton"), "nigerpeton");
	public static ModelLayerLocation NIGERPETON_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "nigerpeton_frame"), "nigerpeton_frame");
	public static ModelLayerLocation ARIZONASAURUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "arizonasaurus"), "arizonasaurus");
	public static ModelLayerLocation ARIZONASAURUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "arizonasaurus_frame"), "arizonasaurus_frame");
	public static ModelLayerLocation POPOSAURUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "poposaurus"), "poposaurus");
	public static ModelLayerLocation POPOSAURUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "poposaurus_frame"), "poposaurus_frame");
	public static ModelLayerLocation STAHLECKERIA = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "stahleckeria"), "stahleckeria");
	public static ModelLayerLocation STAHLECKERIA_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "stahleckeria_frame"), "stahleckeria_frame");
	public static ModelLayerLocation STAGONOLEPIS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "stagonolepis"), "stagonolepis");
	public static ModelLayerLocation STAGONOLEPIS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "stagonolepis_frame"), "stagonolepis_frame");
	public static ModelLayerLocation GUANLONG = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "guanlong"), "guanlong");
	public static ModelLayerLocation GUANLONG_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "guanlong_frame"), "guanlong_frame");
	public static ModelLayerLocation ICHTHYOSAURUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "ichthyosaurus"), "ichthyosaurus");
	public static ModelLayerLocation ICHTHYOSAURUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "ichthyosaurus_frame"), "ichthyosaurus_frame");
	public static ModelLayerLocation SCELIDOSAURUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "scelidosaurus"), "scelidosaurus");
	public static ModelLayerLocation SCELIDOSAURUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "scelidosaurus_frame"), "scelidosaurus_frame");
	public static ModelLayerLocation WUERHOSAURUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "wuerhosaurus"), "wuerhosaurus");
	public static ModelLayerLocation WUERHOSAURUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "wuerhosaurus_frame"), "wuerhosaurus_frame");
	public static ModelLayerLocation BISONLATIFRONS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "bisonlatifrons"), "bisonlatifrons");
	public static ModelLayerLocation BISONLATIFRONS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "bisonlatifrons_frame"), "bisonlatifrons_frame");
	public static ModelLayerLocation SMILOSUCHUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "smilosuchus"), "smilosuchus");
	public static ModelLayerLocation SMILOSUCHUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "smilosuchus_frame"), "smilosuchus_frame");
	public static ModelLayerLocation UTAHRAPTOR = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "utahraptor"), "utahraptor");
	public static ModelLayerLocation UTAHRAPTOR_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "utahraptor_frame"), "utahraptor_frame");
	public static ModelLayerLocation SHONISAURUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "shonisaurus"), "shonisaurus");
	public static ModelLayerLocation SHONISAURUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "shonisaurus_frame"), "shonisaurus_frame");

	@SubscribeEvent
	public static void registerLayerDefinition(EntityRenderersEvent.RegisterLayerDefinitions event) {
		event.registerLayerDefinition(TROPAEUM, TropaeumFossilSlabModel::createBodyLayer);
		event.registerLayerDefinition(ALIENUM, AlienumFossilSlabModel::createBodyLayer);
		event.registerLayerDefinition(EUNOTOSAURUS, EunotosaurusFossilModel::createBodyLayer);
		event.registerLayerDefinition(EUNOTOSAURUS_FRAME, EunotosaurusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(PELECANIMIMUS, PelecanimimusFossilModel::createBodyLayer);
		event.registerLayerDefinition(PELECANIMIMUS_FRAME, PelecanimimusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(STENOKRANIO, StenokranioFossilModel::createBodyLayer);
		event.registerLayerDefinition(STENOKRANIO_FRAME, StenokranioFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(HENODUS, HenodusFossilModel::createBodyLayer);
		event.registerLayerDefinition(HENODUS_FRAME, HenodusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(ACANTHOSTEGA, AcanthostegaFossilModel::createBodyLayer);
		event.registerLayerDefinition(ACANTHOSTEGA_FRAME, AcanthostegaFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(PROTOCERAS, ProtocerasFossilModel::createBodyLayer);
		event.registerLayerDefinition(PROTOCERAS_FRAME, ProtocerasFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(DIPLOCAULUSMAGNICORNIS, DiplocaulusmagnicornisFossilModel::createBodyLayer);
		event.registerLayerDefinition(DIPLOCAULUSMAGNICORNIS_FRAME, DiplocaulusmagnicornisFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(TIKTAALIK, TiktaalikFossilModel::createBodyLayer);
		event.registerLayerDefinition(TIKTAALIK_FRAME, TiktaalikFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(SUMINIA, SuminiaFossilModel::createBodyLayer);
		event.registerLayerDefinition(SUMINIA_FRAME, SuminiaFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(MEGALANCOSAURUS, MegalancosaurusFossilModel::createBodyLayer);
		event.registerLayerDefinition(MEGALANCOSAURUS_FRAME, MegalancosaurusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(RIOJASUCHUS, RiojasuchusFossilModel::createBodyLayer);
		event.registerLayerDefinition(RIOJASUCHUS_FRAME, RiojasuchusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(DREPANOSAURUS, DrepanosaurusFossilModel::createBodyLayer);
		event.registerLayerDefinition(DREPANOSAURUS_FRAME, DrepanosaurusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(MANIDENS, ManidensFossilModel::createBodyLayer);
		event.registerLayerDefinition(MANIDENS_FRAME, ManidensFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(KENTROSAURUS, KentrosaurusFossilModel::createBodyLayer);
		event.registerLayerDefinition(KENTROSAURUS_FRAME, KentrosaurusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(NASUTOCERATOPS, NasutoceratopsFossilModel::createBodyLayer);
		event.registerLayerDefinition(NASUTOCERATOPS_FRAME, NasutoceratopsFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(SYNTHETOCERAS, SynthetocerasFossilModel::createBodyLayer);
		event.registerLayerDefinition(SYNTHETOCERAS_FRAME, SynthetocerasFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(DIMETRODONGRANDIS, DimetrodonFossilModel::createBodyLayer);
		event.registerLayerDefinition(DIMETRODONGRANDIS_FRAME, DimetrodonFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(PLACERIAS, PlaceriasFossilModel::createBodyLayer);
		event.registerLayerDefinition(PLACERIAS_FRAME, PlaceriasFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(ENDOTHIODONBATHYSTOMA, EndothiodonbathystomaFossilModel::createBodyLayer);
		event.registerLayerDefinition(ENDOTHIODONBATHYSTOMA_FRAME, EndothiodonbathystomaFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(NIGERPETON, NigerpetonFossilModel::createBodyLayer);
		event.registerLayerDefinition(NIGERPETON_FRAME, NigerpetonFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(ARIZONASAURUS, ArizonasaurusFossilModel::createBodyLayer);
		event.registerLayerDefinition(ARIZONASAURUS_FRAME, ArizonasaurusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(POPOSAURUS, PoposaurusFossilModel::createBodyLayer);
		event.registerLayerDefinition(POPOSAURUS_FRAME, PoposaurusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(STAHLECKERIA, StahleckeriaFossilModel::createBodyLayer);
		event.registerLayerDefinition(STAHLECKERIA_FRAME, StahleckeriaFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(STAGONOLEPIS, StagonolepisFossilModel::createBodyLayer);
		event.registerLayerDefinition(STAGONOLEPIS_FRAME, StagonolepisFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(GUANLONG, GuanlongFossilModel::createBodyLayer);
		event.registerLayerDefinition(GUANLONG_FRAME, GuanlongFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(ICHTHYOSAURUS, IchthyosaurusFossilModel::createBodyLayer);
		event.registerLayerDefinition(ICHTHYOSAURUS_FRAME, IchthyosaurusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(SCELIDOSAURUS, ScelidosaurusFossilModel::createBodyLayer);
		event.registerLayerDefinition(SCELIDOSAURUS_FRAME, ScelidosaurusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(WUERHOSAURUS, WuerhosaurusFossilModel::createBodyLayer);
		event.registerLayerDefinition(WUERHOSAURUS_FRAME, WuerhosaurusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(BISONLATIFRONS, BisonlatifronsFossilModel::createBodyLayer);
		event.registerLayerDefinition(BISONLATIFRONS_FRAME, BisonlatifronsFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(SMILOSUCHUS, SmilosuchusFossilModel::createBodyLayer);
		event.registerLayerDefinition(SMILOSUCHUS_FRAME, SmilosuchusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(UTAHRAPTOR, UtahraptorFossilModel::createBodyLayer);
		event.registerLayerDefinition(UTAHRAPTOR_FRAME, UtahraptorFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(SHONISAURUS, ShonisaurusFossilModel::createBodyLayer);
		event.registerLayerDefinition(SHONISAURUS_FRAME, ShonisaurusFossilFrameModel::createBodyLayer);
	}
	
	@SubscribeEvent
	public static void init(final FMLClientSetupEvent event) {
		ClientProxy.setupBlockRenders();
	}
	
}
