package fossils.fossils.client;

import fossils.fossils.FossilMod;
import fossils.fossils.client.blockentity.model.AlienumFossilSlabModel;
import fossils.fossils.client.blockentity.model.TropaeumFossilSlabModel;
import fossils.fossils.client.blockentity.model.abyssosaurus.AbyssosaurusFossilFrameModel;
import fossils.fossils.client.blockentity.model.abyssosaurus.AbyssosaurusFossilModel;
import fossils.fossils.client.blockentity.model.acanthostega.AcanthostegaFossilFrameModel;
import fossils.fossils.client.blockentity.model.acanthostega.AcanthostegaFossilModel;
import fossils.fossils.client.blockentity.model.allosaurus.AllosaurusFossilFrameModel;
import fossils.fossils.client.blockentity.model.allosaurus.AllosaurusFossilModel;
import fossils.fossils.client.blockentity.model.amargasaurus.AmargasaurusFossilFrameModel;
import fossils.fossils.client.blockentity.model.amargasaurus.AmargasaurusFossilModel;
import fossils.fossils.client.blockentity.model.anatosuchus.AnatosuchusFossilFrameModel;
import fossils.fossils.client.blockentity.model.anatosuchus.AnatosuchusFossilModel;
import fossils.fossils.client.blockentity.model.apatosaurus.ApatosaurusFossilFrameModel;
import fossils.fossils.client.blockentity.model.apatosaurus.ApatosaurusFossilModel;
import fossils.fossils.client.blockentity.model.aquilops.AquilopsFossilFrameModel;
import fossils.fossils.client.blockentity.model.aquilops.AquilopsFossilModel;
import fossils.fossils.client.blockentity.model.arizonasaurus.ArizonasaurusFossilFrameModel;
import fossils.fossils.client.blockentity.model.arizonasaurus.ArizonasaurusFossilModel;
import fossils.fossils.client.blockentity.model.bannykus.BannykusFossilFrameModel;
import fossils.fossils.client.blockentity.model.bannykus.BannykusFossilModel;
import fossils.fossils.client.blockentity.model.bisonlatifrons.BisonlatifronsFossilFrameModel;
import fossils.fossils.client.blockentity.model.bisonlatifrons.BisonlatifronsFossilModel;
import fossils.fossils.client.blockentity.model.brachiosaurus.BrachiosaurusFossilFrameModel;
import fossils.fossils.client.blockentity.model.brachiosaurus.BrachiosaurusFossilModel;
import fossils.fossils.client.blockentity.model.brachytrachelopan.BrachytrachelopanFossilFrameModel;
import fossils.fossils.client.blockentity.model.brachytrachelopan.BrachytrachelopanFossilModel;
import fossils.fossils.client.blockentity.model.camptosaurus.CamptosaurusFossilFrameModel;
import fossils.fossils.client.blockentity.model.camptosaurus.CamptosaurusFossilModel;
import fossils.fossils.client.blockentity.model.carcharodontosaurus.CarcharodontosaurusFossilFrameModel;
import fossils.fossils.client.blockentity.model.carcharodontosaurus.CarcharodontosaurusFossilModel;
import fossils.fossils.client.blockentity.model.ceratosaurusdentisulcatus.CeratosaurusdentisulcatusFossilFrameModel;
import fossils.fossils.client.blockentity.model.ceratosaurusdentisulcatus.CeratosaurusdentisulcatusFossilModel;
import fossils.fossils.client.blockentity.model.coelophysis.CoelophysisFossilFrameModel;
import fossils.fossils.client.blockentity.model.coelophysis.CoelophysisFossilModel;
import fossils.fossils.client.blockentity.model.cotylorhynchus.CotylorhynchusFossilFrameModel;
import fossils.fossils.client.blockentity.model.cotylorhynchus.CotylorhynchusFossilModel;
import fossils.fossils.client.blockentity.model.cryolophosaurus.CryolophosaurusFossilFrameModel;
import fossils.fossils.client.blockentity.model.cryolophosaurus.CryolophosaurusFossilModel;
import fossils.fossils.client.blockentity.model.dasyceps.DasycepsFossilFrameModel;
import fossils.fossils.client.blockentity.model.dasyceps.DasycepsFossilModel;
import fossils.fossils.client.blockentity.model.dearc.DearcFossilFrameModel;
import fossils.fossils.client.blockentity.model.dearc.DearcFossilModel;
import fossils.fossils.client.blockentity.model.decennatherium.DecennatheriumFossilFrameModel;
import fossils.fossils.client.blockentity.model.decennatherium.DecennatheriumFossilModel;
import fossils.fossils.client.blockentity.model.deinonychus.DeinonychusFossilFrameModel;
import fossils.fossils.client.blockentity.model.deinonychus.DeinonychusFossilModel;
import fossils.fossils.client.blockentity.model.dilophosaurus.DilophosaurusFossilFrameModel;
import fossils.fossils.client.blockentity.model.dilophosaurus.DilophosaurusFossilModel;
import fossils.fossils.client.blockentity.model.dimetrodongrandis.DimetrodonFossilFrameModel;
import fossils.fossils.client.blockentity.model.dimetrodongrandis.DimetrodonFossilModel;
import fossils.fossils.client.blockentity.model.dinocrocuta.DinocrocutaFossilFrameModel;
import fossils.fossils.client.blockentity.model.dinocrocuta.DinocrocutaFossilModel;
import fossils.fossils.client.blockentity.model.diplocaulusmagnicornis.DiplocaulusmagnicornisFossilFrameModel;
import fossils.fossils.client.blockentity.model.diplocaulusmagnicornis.DiplocaulusmagnicornisFossilModel;
import fossils.fossils.client.blockentity.model.dorudon.DorudonFossilFrameModel;
import fossils.fossils.client.blockentity.model.dorudon.DorudonFossilModel;
import fossils.fossils.client.blockentity.model.drepanosaurus.DrepanosaurusFossilFrameModel;
import fossils.fossils.client.blockentity.model.drepanosaurus.DrepanosaurusFossilModel;
import fossils.fossils.client.blockentity.model.edmontosaurusannectens.EdmontosaurusannectensFossilFrameModel;
import fossils.fossils.client.blockentity.model.edmontosaurusannectens.EdmontosaurusannectensFossilModel;
import fossils.fossils.client.blockentity.model.endothiodonbathystoma.EndothiodonbathystomaFossilFrameModel;
import fossils.fossils.client.blockentity.model.endothiodonbathystoma.EndothiodonbathystomaFossilModel;
import fossils.fossils.client.blockentity.model.eoabelisaurus.EoabelisaurusFossilFrameModel;
import fossils.fossils.client.blockentity.model.eoabelisaurus.EoabelisaurusFossilModel;
import fossils.fossils.client.blockentity.model.eremotherium.EremotheriumFossilFrameModel;
import fossils.fossils.client.blockentity.model.eremotherium.EremotheriumFossilModel;
import fossils.fossils.client.blockentity.model.eunotosaurus.EunotosaurusFossilFrameModel;
import fossils.fossils.client.blockentity.model.eunotosaurus.EunotosaurusFossilModel;
import fossils.fossils.client.blockentity.model.gastornis.GastornisFossilFrameModel;
import fossils.fossils.client.blockentity.model.gastornis.GastornisFossilModel;
import fossils.fossils.client.blockentity.model.guanlong.GuanlongFossilFrameModel;
import fossils.fossils.client.blockentity.model.guanlong.GuanlongFossilModel;
import fossils.fossils.client.blockentity.model.hatzegopteryx.HatzegopteryxFossilFrameModel;
import fossils.fossils.client.blockentity.model.hatzegopteryx.HatzegopteryxFossilModel;
import fossils.fossils.client.blockentity.model.henodus.HenodusFossilFrameModel;
import fossils.fossils.client.blockentity.model.henodus.HenodusFossilModel;
import fossils.fossils.client.blockentity.model.huaxiazhoulong.HuaxiazhoulongFossilFrameModel;
import fossils.fossils.client.blockentity.model.huaxiazhoulong.HuaxiazhoulongFossilModel;
import fossils.fossils.client.blockentity.model.ichthyosaurus.IchthyosaurusFossilFrameModel;
import fossils.fossils.client.blockentity.model.ichthyosaurus.IchthyosaurusFossilModel;
import fossils.fossils.client.blockentity.model.iguanodon.IguanodonFossilFrameModel;
import fossils.fossils.client.blockentity.model.iguanodon.IguanodonFossilModel;
import fossils.fossils.client.blockentity.model.kentrosaurus.KentrosaurusFossilFrameModel;
import fossils.fossils.client.blockentity.model.kentrosaurus.KentrosaurusFossilModel;
import fossils.fossils.client.blockentity.model.koolasuchus.KoolasuchusFossilFrameModel;
import fossils.fossils.client.blockentity.model.koolasuchus.KoolasuchusFossilModel;
import fossils.fossils.client.blockentity.model.kubanochoerus.KubanochoerusFossilFrameModel;
import fossils.fossils.client.blockentity.model.kubanochoerus.KubanochoerusFossilModel;
import fossils.fossils.client.blockentity.model.kutchicetus.KutchicetusFossilFrameModel;
import fossils.fossils.client.blockentity.model.kutchicetus.KutchicetusFossilModel;
import fossils.fossils.client.blockentity.model.manidens.ManidensFossilFrameModel;
import fossils.fossils.client.blockentity.model.manidens.ManidensFossilModel;
import fossils.fossils.client.blockentity.model.megacerops.MegaceropsFossilFrameModel;
import fossils.fossils.client.blockentity.model.megacerops.MegaceropsFossilModel;
import fossils.fossils.client.blockentity.model.megalancosaurus.MegalancosaurusFossilFrameModel;
import fossils.fossils.client.blockentity.model.megalancosaurus.MegalancosaurusFossilModel;
import fossils.fossils.client.blockentity.model.mei.MeiFossilFrameModel;
import fossils.fossils.client.blockentity.model.mei.MeiFossilModel;
import fossils.fossils.client.blockentity.model.montanoceratops.MontanoceratopsFossilFrameModel;
import fossils.fossils.client.blockentity.model.montanoceratops.MontanoceratopsFossilModel;
import fossils.fossils.client.blockentity.model.muttaburrasaurus.MuttaburrasaurusFossilFrameModel;
import fossils.fossils.client.blockentity.model.muttaburrasaurus.MuttaburrasaurusFossilModel;
import fossils.fossils.client.blockentity.model.nasutoceratops.NasutoceratopsFossilFrameModel;
import fossils.fossils.client.blockentity.model.nasutoceratops.NasutoceratopsFossilModel;
import fossils.fossils.client.blockentity.model.nigerpeton.NigerpetonFossilFrameModel;
import fossils.fossils.client.blockentity.model.nigerpeton.NigerpetonFossilModel;
import fossils.fossils.client.blockentity.model.nigersaurus.NigersaurusFossilFrameModel;
import fossils.fossils.client.blockentity.model.nigersaurus.NigersaurusFossilModel;
import fossils.fossils.client.blockentity.model.nqwebasaurus.NqwebasaurusFossilFrameModel;
import fossils.fossils.client.blockentity.model.nqwebasaurus.NqwebasaurusFossilModel;
import fossils.fossils.client.blockentity.model.pantheratigris.PantheratigrisFossilFrameModel;
import fossils.fossils.client.blockentity.model.pantheratigris.PantheratigrisFossilModel;
import fossils.fossils.client.blockentity.model.patagosaurus.PatagosaurusFossilFrameModel;
import fossils.fossils.client.blockentity.model.patagosaurus.PatagosaurusFossilModel;
import fossils.fossils.client.blockentity.model.pelecanimimus.PelecanimimusFossilFrameModel;
import fossils.fossils.client.blockentity.model.pelecanimimus.PelecanimimusFossilModel;
import fossils.fossils.client.blockentity.model.piatnitzkysaurus.PiatnitzkysaurusFossilFrameModel;
import fossils.fossils.client.blockentity.model.piatnitzkysaurus.PiatnitzkysaurusFossilModel;
import fossils.fossils.client.blockentity.model.placerias.PlaceriasFossilFrameModel;
import fossils.fossils.client.blockentity.model.placerias.PlaceriasFossilModel;
import fossils.fossils.client.blockentity.model.pliosaurus.PliosaurusFossilFrameModel;
import fossils.fossils.client.blockentity.model.pliosaurus.PliosaurusFossilModel;
import fossils.fossils.client.blockentity.model.poposaurus.PoposaurusFossilFrameModel;
import fossils.fossils.client.blockentity.model.poposaurus.PoposaurusFossilModel;
import fossils.fossils.client.blockentity.model.prodinoceras.ProdinocerasFossilFrameModel;
import fossils.fossils.client.blockentity.model.prodinoceras.ProdinocerasFossilModel;
import fossils.fossils.client.blockentity.model.protoceras.ProtocerasFossilFrameModel;
import fossils.fossils.client.blockentity.model.protoceras.ProtocerasFossilModel;
import fossils.fossils.client.blockentity.model.protoceratopsandrewsi.ProtoceratopsandrewsiFossilFrameModel;
import fossils.fossils.client.blockentity.model.protoceratopsandrewsi.ProtoceratopsandrewsiFossilModel;
import fossils.fossils.client.blockentity.model.regaliceratops.RegaliceratopsFossilFrameModel;
import fossils.fossils.client.blockentity.model.regaliceratops.RegaliceratopsFossilModel;
import fossils.fossils.client.blockentity.model.riojasuchus.RiojasuchusFossilFrameModel;
import fossils.fossils.client.blockentity.model.riojasuchus.RiojasuchusFossilModel;
import fossils.fossils.client.blockentity.model.sarcosuchus.SarcosuchusFossilFrameModel;
import fossils.fossils.client.blockentity.model.sarcosuchus.SarcosuchusFossilModel;
import fossils.fossils.client.blockentity.model.sauropelta.SauropeltaFossilFrameModel;
import fossils.fossils.client.blockentity.model.sauropelta.SauropeltaFossilModel;
import fossils.fossils.client.blockentity.model.scelidosaurus.ScelidosaurusFossilFrameModel;
import fossils.fossils.client.blockentity.model.scelidosaurus.ScelidosaurusFossilModel;
import fossils.fossils.client.blockentity.model.shonisaurus.ShonisaurusFossilFrameModel;
import fossils.fossils.client.blockentity.model.shonisaurus.ShonisaurusFossilModel;
import fossils.fossils.client.blockentity.model.shuvuuia.ShuvuuiaFossilFrameModel;
import fossils.fossils.client.blockentity.model.shuvuuia.ShuvuuiaFossilModel;
import fossils.fossils.client.blockentity.model.silesaurus.SilesaurusFossilFrameModel;
import fossils.fossils.client.blockentity.model.silesaurus.SilesaurusFossilModel;
import fossils.fossils.client.blockentity.model.sinclairomeryx.SinclairomeryxFossilFrameModel;
import fossils.fossils.client.blockentity.model.sinclairomeryx.SinclairomeryxFossilModel;
import fossils.fossils.client.blockentity.model.skorpiovenator.SkorpiovenatorFossilFrameModel;
import fossils.fossils.client.blockentity.model.skorpiovenator.SkorpiovenatorFossilModel;
import fossils.fossils.client.blockentity.model.smilosuchus.SmilosuchusFossilFrameModel;
import fossils.fossils.client.blockentity.model.smilosuchus.SmilosuchusFossilModel;
import fossils.fossils.client.blockentity.model.spinosaurus.SpinosaurusFossilFrameModel;
import fossils.fossils.client.blockentity.model.spinosaurus.SpinosaurusFossilModel;
import fossils.fossils.client.blockentity.model.stagonolepis.StagonolepisFossilFrameModel;
import fossils.fossils.client.blockentity.model.stagonolepis.StagonolepisFossilModel;
import fossils.fossils.client.blockentity.model.stahleckeria.StahleckeriaFossilFrameModel;
import fossils.fossils.client.blockentity.model.stahleckeria.StahleckeriaFossilModel;
import fossils.fossils.client.blockentity.model.stenokranio.StenokranioFossilFrameModel;
import fossils.fossils.client.blockentity.model.stenokranio.StenokranioFossilModel;
import fossils.fossils.client.blockentity.model.struthiomimus.StruthiomimusFossilFrameModel;
import fossils.fossils.client.blockentity.model.struthiomimus.StruthiomimusFossilModel;
import fossils.fossils.client.blockentity.model.suminia.SuminiaFossilFrameModel;
import fossils.fossils.client.blockentity.model.suminia.SuminiaFossilModel;
import fossils.fossils.client.blockentity.model.synthetoceras.SynthetocerasFossilFrameModel;
import fossils.fossils.client.blockentity.model.synthetoceras.SynthetocerasFossilModel;
import fossils.fossils.client.blockentity.model.tethyshadros.TethyshadrosFossilFrameModel;
import fossils.fossils.client.blockentity.model.tethyshadros.TethyshadrosFossilModel;
import fossils.fossils.client.blockentity.model.thylacoleo.ThylacoleoFossilFrameModel;
import fossils.fossils.client.blockentity.model.thylacoleo.ThylacoleoFossilModel;
import fossils.fossils.client.blockentity.model.tiktaalik.TiktaalikFossilFrameModel;
import fossils.fossils.client.blockentity.model.tiktaalik.TiktaalikFossilModel;
import fossils.fossils.client.blockentity.model.tupandactylusnavigans.TupandactylusnavigansFossilFrameModel;
import fossils.fossils.client.blockentity.model.tupandactylusnavigans.TupandactylusnavigansFossilModel;
import fossils.fossils.client.blockentity.model.tyrannosaurus.TyrannosaurusFossilFrameModel;
import fossils.fossils.client.blockentity.model.tyrannosaurus.TyrannosaurusFossilModel;
import fossils.fossils.client.blockentity.model.utahraptor.UtahraptorFossilFrameModel;
import fossils.fossils.client.blockentity.model.utahraptor.UtahraptorFossilModel;
import fossils.fossils.client.blockentity.model.velociraptor.VelociraptorFossilFrameModel;
import fossils.fossils.client.blockentity.model.velociraptor.VelociraptorFossilModel;
import fossils.fossils.client.blockentity.model.wuerhosaurus.WuerhosaurusFossilFrameModel;
import fossils.fossils.client.blockentity.model.wuerhosaurus.WuerhosaurusFossilModel;
import fossils.fossils.client.blockentity.model.yingshanosaurus.YingshanosaurusFossilFrameModel;
import fossils.fossils.client.blockentity.model.yingshanosaurus.YingshanosaurusFossilModel;
import fossils.fossils.client.blockentity.model.yuanyanglong.YuanyanglongFossilFrameModel;
import fossils.fossils.client.blockentity.model.yuanyanglong.YuanyanglongFossilModel;
import fossils.fossils.client.blockentity.render.FossilSkeletonFifteenPieceRenderer;
import fossils.fossils.client.blockentity.render.FossilSkeletonFivePieceRenderer;
import fossils.fossils.client.blockentity.render.FossilSkeletonTenPieceRenderer;
import fossils.fossils.client.blockentity.render.FossilSkeletonTwentyPieceRenderer;
import fossils.fossils.client.blockentity.render.FossilSlabRenderer;
import fossils.fossils.init.FossilBlockEntities;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.resources.ResourceLocation;
import net.minecraftforge.api.distmarker.Dist;
import net.minecraftforge.api.distmarker.OnlyIn;
import net.minecraftforge.client.event.EntityRenderersEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;

@OnlyIn(Dist.CLIENT)
@Mod.EventBusSubscriber(modid = FossilMod.MOD_ID, bus = Mod.EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)
public class ClientEvents {

	@SubscribeEvent
	public static void registerEntityRenders(EntityRenderersEvent.RegisterRenderers event) {
		event.registerBlockEntityRenderer(FossilBlockEntities.FOSSIL_SLAB.get(), FossilSlabRenderer::new);
		event.registerBlockEntityRenderer(FossilBlockEntities.FOSSIL_SKELETON_FIVE_PIECE.get(), FossilSkeletonFivePieceRenderer::new);
		event.registerBlockEntityRenderer(FossilBlockEntities.FOSSIL_SKELETON_TEN_PIECE.get(), FossilSkeletonTenPieceRenderer::new);
		event.registerBlockEntityRenderer(FossilBlockEntities.FOSSIL_SKELETON_FIFTEEN_PIECE.get(), FossilSkeletonFifteenPieceRenderer::new);
		event.registerBlockEntityRenderer(FossilBlockEntities.FOSSIL_SKELETON_TWENTY_PIECE.get(), FossilSkeletonTwentyPieceRenderer::new);
	}

	public static ModelLayerLocation TROPAEUM = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "tropaeum"), "tropaeum");
	public static ModelLayerLocation ALIENUM = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "alienum"), "alienum");
	public static ModelLayerLocation EUNOTOSAURUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "eunotosaurus"), "eunotosaurus");
	public static ModelLayerLocation EUNOTOSAURUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "eunotosaurus_frame"), "eunotosaurus_frame");
	public static ModelLayerLocation PELECANIMIMUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "pelecanimimus"), "pelecanimimus");
	public static ModelLayerLocation PELECANIMIMUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "pelecanimimus_frame"), "pelecanimimus_frame");
	public static ModelLayerLocation STENOKRANIO = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "stenokranio"), "stenokranio");
	public static ModelLayerLocation STENOKRANIO_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "stenokranio_frame"), "stenokranio_frame");
	public static ModelLayerLocation HENODUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "henodus"), "henodus");
	public static ModelLayerLocation HENODUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "henodus_frame"), "henodus_frame");
	public static ModelLayerLocation ACANTHOSTEGA = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "acanthostega"), "acanthostega");
	public static ModelLayerLocation ACANTHOSTEGA_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "acanthostega_frame"), "acanthostega_frame");
	public static ModelLayerLocation PROTOCERAS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "protoceras"), "protoceras");
	public static ModelLayerLocation PROTOCERAS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "protoceras_frame"), "protoceras_frame");
	public static ModelLayerLocation DIPLOCAULUSMAGNICORNIS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "diplocaulusmagnicornis"), "diplocaulusmagnicornis");
	public static ModelLayerLocation DIPLOCAULUSMAGNICORNIS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "diplocaulusmagnicornis_frame"), "diplocaulusmagnicornis_frame");
	public static ModelLayerLocation TIKTAALIK = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "tiktaalik"), "tiktaalik");
	public static ModelLayerLocation TIKTAALIK_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "tiktaalik_frame"), "tiktaalik_frame");
	public static ModelLayerLocation SUMINIA = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "suminia"), "suminia");
	public static ModelLayerLocation SUMINIA_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "suminia_frame"), "suminia_frame");
	public static ModelLayerLocation MEGALANCOSAURUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "megalancosaurus"), "megalancosaurus");
	public static ModelLayerLocation MEGALANCOSAURUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "megalancosaurus_frame"), "megalancosaurus_frame");
	public static ModelLayerLocation RIOJASUCHUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "riojasuchus"), "riojasuchus");
	public static ModelLayerLocation RIOJASUCHUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "riojasuchus_frame"), "riojasuchus_frame");
	public static ModelLayerLocation DREPANOSAURUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "drepanosaurus"), "drepanosaurus");
	public static ModelLayerLocation DREPANOSAURUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "drepanosaurus_frame"), "drepanosaurus_frame");
	public static ModelLayerLocation MANIDENS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "manidens"), "manidens");
	public static ModelLayerLocation MANIDENS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "manidens_frame"), "manidens_frame");
	public static ModelLayerLocation DASYCEPS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "dasyceps"), "dasyceps");
	public static ModelLayerLocation DASYCEPS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "dasyceps_frame"), "dasyceps_frame");
	public static ModelLayerLocation AQUILOPS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "aquilops"), "aquilops");
	public static ModelLayerLocation AQUILOPS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "aquilops_frame"), "aquilops_frame");
	public static ModelLayerLocation BANNYKUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "bannykus"), "bannykus");
	public static ModelLayerLocation BANNYKUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "bannykus_frame"), "bannykus_frame");
	public static ModelLayerLocation YUANYANGLONG = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "yuanyanglong"), "yuanyanglong");
	public static ModelLayerLocation YUANYANGLONG_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "yuanyanglong_frame"), "yuanyanglong_frame");
	public static ModelLayerLocation MEI = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "mei"), "mei");
	public static ModelLayerLocation MEI_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "mei_frame"), "mei_frame");
	public static ModelLayerLocation ANATOSUCHUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "anatosuchus"), "anatosuchus");
	public static ModelLayerLocation ANATOSUCHUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "anatosuchus_frame"), "anatosuchus_frame");
	public static ModelLayerLocation NQWEBASAURUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "nqwebasaurus"), "nqwebasaurus");
	public static ModelLayerLocation NQWEBASAURUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "nqwebasaurus_frame"), "nqwebasaurus_frame");
	public static ModelLayerLocation SHUVUUIA = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "shuvuuia"), "shuvuuia");
	public static ModelLayerLocation SHUVUUIA_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "shuvuuia_frame"), "shuvuuia_frame");
	public static ModelLayerLocation SILESAURUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "silesaurus"), "silesaurus");
	public static ModelLayerLocation SILESAURUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "silesaurus_frame"), "silesaurus_frame");
	public static ModelLayerLocation KENTROSAURUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "kentrosaurus"), "kentrosaurus");
	public static ModelLayerLocation KENTROSAURUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "kentrosaurus_frame"), "kentrosaurus_frame");
	public static ModelLayerLocation PIATNITZKYSAURUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "piatnitzkysaurus"), "piatnitzkysaurus");
	public static ModelLayerLocation PIATNITZKYSAURUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "piatnitzkysaurus_frame"), "piatnitzkysaurus_frame");
	public static ModelLayerLocation DEARC = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "dearc"), "dearc");
	public static ModelLayerLocation DEARC_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "dearc_frame"), "dearc_frame");
	public static ModelLayerLocation NASUTOCERATOPS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "nasutoceratops"), "nasutoceratops");
	public static ModelLayerLocation NASUTOCERATOPS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "nasutoceratops_frame"), "nasutoceratops_frame");
	public static ModelLayerLocation SYNTHETOCERAS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "synthetoceras"), "synthetoceras");
	public static ModelLayerLocation SYNTHETOCERAS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "synthetoceras_frame"), "synthetoceras_frame");
	public static ModelLayerLocation DIMETRODONGRANDIS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "dimetrodongrandis"), "dimetrodongrandis");
	public static ModelLayerLocation DIMETRODONGRANDIS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "dimetrodongrandis_frame"), "dimetrodongrandis_frame");
	public static ModelLayerLocation TUPANDACTYLUSNAVIGANS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "tupandactylusnavigans"), "tupandactylusnavigans");
	public static ModelLayerLocation TUPANDACTYLUSNAVIGANS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "tupandactylusnavigans_frame"), "tupandactylusnavigans_frame");
	public static ModelLayerLocation SKORPIOVENATOR= new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "skorpiovenator"), "skorpiovenator");
	public static ModelLayerLocation SKORPIOVENATOR_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "skorpiovenator_frame"), "skorpiovenator_frame");
	public static ModelLayerLocation PROTOCERATOPSANDREWSI= new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "protoceratopsandrewsi"), "protoceratopsandrewsi");
	public static ModelLayerLocation PROTOCERATOPSANDREWSI_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "protoceratopsandrewsi_frame"), "protoceratopsandrewsi_frame");
	public static ModelLayerLocation STRUTHIOMIMUS= new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "struthiomimus"), "struthiomimus");
	public static ModelLayerLocation STRUTHIOMIMUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "struthiomimus_frame"), "struthiomimus_frame");
	public static ModelLayerLocation MONTANOCERATOPS= new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "montanoceratops"), "montanoceratops");
	public static ModelLayerLocation MONTANOCERATOPS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "montanoceratops_frame"), "montanoceratops_frame");
	public static ModelLayerLocation DORUDON= new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "dorudon"), "dorudon");
	public static ModelLayerLocation DORUDON_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "dorudon_frame"), "dorudon_frame");
	public static ModelLayerLocation GASTORNIS= new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "gastornis"), "gastornis");
	public static ModelLayerLocation GASTORNIS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "gastornis_frame"), "gastornis_frame");
	public static ModelLayerLocation KUTCHICETUS= new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "kutchicetus"), "kutchicetus");
	public static ModelLayerLocation KUTCHICETUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "kutchicetus_frame"), "kutchicetus_frame");
	public static ModelLayerLocation PRODINOCERAS= new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "prodinoceras"), "prodinoceras");
	public static ModelLayerLocation PRODINOCERAS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "prodinoceras_frame"), "prodinoceras_frame");
	public static ModelLayerLocation THYLACOLEO= new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "thylacoleo"), "thylacoleo");
	public static ModelLayerLocation THYLACOLEO_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "thylacoleo_frame"), "thylacoleo_frame");
	public static ModelLayerLocation SINCLAIROMERYX= new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "sinclairomeryx"), "sinclairomeryx");
	public static ModelLayerLocation SINCLAIROMERYX_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "sinclairomeryx_frame"), "sinclairomeryx_frame");
	public static ModelLayerLocation DINOCROCUTA= new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "dinocrocuta"), "dinocrocuta");
	public static ModelLayerLocation DINOCROCUTA_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "dinocrocuta_frame"), "dinocrocuta_frame");
	public static ModelLayerLocation COELOPHYSIS= new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "coelophysis"), "coelophysis");
	public static ModelLayerLocation COELOPHYSIS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "coelophysis_frame"), "coelophysis_frame");
	public static ModelLayerLocation PLACERIAS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "placerias"), "placerias");
	public static ModelLayerLocation PLACERIAS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "placerias_frame"), "placerias_frame");
	public static ModelLayerLocation ENDOTHIODONBATHYSTOMA = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "endothiodonbathystoma"), "endothiodonbathystoma");
	public static ModelLayerLocation ENDOTHIODONBATHYSTOMA_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "endothiodonbathystoma_frame"), "endothiodonbathystoma_frame");
	public static ModelLayerLocation NIGERPETON = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "nigerpeton"), "nigerpeton");
	public static ModelLayerLocation NIGERPETON_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "nigerpeton_frame"), "nigerpeton_frame");
	public static ModelLayerLocation ARIZONASAURUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "arizonasaurus"), "arizonasaurus");
	public static ModelLayerLocation ARIZONASAURUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "arizonasaurus_frame"), "arizonasaurus_frame");
	public static ModelLayerLocation POPOSAURUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "poposaurus"), "poposaurus");
	public static ModelLayerLocation POPOSAURUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "poposaurus_frame"), "poposaurus_frame");
	public static ModelLayerLocation STAHLECKERIA = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "stahleckeria"), "stahleckeria");
	public static ModelLayerLocation STAHLECKERIA_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "stahleckeria_frame"), "stahleckeria_frame");
	public static ModelLayerLocation STAGONOLEPIS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "stagonolepis"), "stagonolepis");
	public static ModelLayerLocation STAGONOLEPIS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "stagonolepis_frame"), "stagonolepis_frame");
	public static ModelLayerLocation GUANLONG = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "guanlong"), "guanlong");
	public static ModelLayerLocation GUANLONG_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "guanlong_frame"), "guanlong_frame");
	public static ModelLayerLocation ICHTHYOSAURUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "ichthyosaurus"), "ichthyosaurus");
	public static ModelLayerLocation ICHTHYOSAURUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "ichthyosaurus_frame"), "ichthyosaurus_frame");
	public static ModelLayerLocation SCELIDOSAURUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "scelidosaurus"), "scelidosaurus");
	public static ModelLayerLocation SCELIDOSAURUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "scelidosaurus_frame"), "scelidosaurus_frame");
	public static ModelLayerLocation WUERHOSAURUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "wuerhosaurus"), "wuerhosaurus");
	public static ModelLayerLocation WUERHOSAURUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "wuerhosaurus_frame"), "wuerhosaurus_frame");
	public static ModelLayerLocation BISONLATIFRONS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "bisonlatifrons"), "bisonlatifrons");
	public static ModelLayerLocation BISONLATIFRONS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "bisonlatifrons_frame"), "bisonlatifrons_frame");
	public static ModelLayerLocation SMILOSUCHUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "smilosuchus"), "smilosuchus");
	public static ModelLayerLocation SMILOSUCHUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "smilosuchus_frame"), "smilosuchus_frame");
	public static ModelLayerLocation CRYOLOPHOSAURUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "cryolophosaurus"), "cryolophosaurus");
	public static ModelLayerLocation CRYOLOPHOSAURUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "cryolophosaurus_frame"), "cryolophosaurus_frame");
	public static ModelLayerLocation DILOPHOSAURUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "dilophosaurus"), "dilophosaurus");
	public static ModelLayerLocation DILOPHOSAURUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "dilophosaurus_frame"), "dilophosaurus_frame");
	public static ModelLayerLocation CERATOSAURUSDENTISULCATUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "ceratosaurusdentisulcatus"), "ceratosaurusdentisulcatus");
	public static ModelLayerLocation CERATOSAURUSDENTISULCATUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "ceratosaurusdentisulcatus_frame"), "ceratosaurusdentisulcatus_frame");
	public static ModelLayerLocation YINGSHANOSAURUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "yingshanosaurus"), "yingshanosaurus");
	public static ModelLayerLocation YINGSHANOSAURUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "yingshanosaurus_frame"), "yingshanosaurus_frame");
	public static ModelLayerLocation PATAGOSAURUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "patagosaurus"), "patagosaurus");
	public static ModelLayerLocation PATAGOSAURUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "patagosaurus_frame"), "patagosaurus_frame");
	public static ModelLayerLocation EOABELISAURUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "eoabelisaurus"), "eoabelisaurus");
	public static ModelLayerLocation EOABELISAURUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "eoabelisaurus_frame"), "eoabelisaurus_frame");
	public static ModelLayerLocation CAMPTOSAURUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "camptosaurus"), "camptosaurus");
	public static ModelLayerLocation CAMPTOSAURUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "camptosaurus_frame"), "camptosaurus_frame");
	public static ModelLayerLocation KOOLASUCHUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "koolasuchus"), "koolasuchus");
	public static ModelLayerLocation KOOLASUCHUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "koolasuchus_frame"), "koolasuchus_frame");
	public static ModelLayerLocation SAUROPELTA = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "sauropelta"), "sauropelta");
	public static ModelLayerLocation SAUROPELTA_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "sauropelta_frame"), "sauropelta_frame");
	public static ModelLayerLocation ABYSSOSAURUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "abyssosaurus"), "abyssosaurus");
	public static ModelLayerLocation ABYSSOSAURUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "abyssosaurus_frame"), "abyssosaurus_frame");
	public static ModelLayerLocation MUTTABURRASAURUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "muttaburrasaurus"), "muttaburrasaurus");
	public static ModelLayerLocation MUTTABURRASAURUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "muttaburrasaurus_frame"), "muttaburrasaurus_frame");
	public static ModelLayerLocation DEINONYCHUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "deinonychus"), "deinonychus");
	public static ModelLayerLocation DEINONYCHUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "deinonychus_frame"), "deinonychus_frame");
	public static ModelLayerLocation BRACHYTRACHELOPAN = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "brachytrachelopan"), "brachytrachelopan");
	public static ModelLayerLocation BRACHYTRACHELOPAN_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "brachytrachelopan_frame"), "brachytrachelopan_frame");
	public static ModelLayerLocation TETHYSHADROS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "tethyshadros"), "tethyshadros");
	public static ModelLayerLocation TETHYSHADROS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "tethyshadros_frame"), "tethyshadros_frame");
	public static ModelLayerLocation REGALICERATOPS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "regaliceratops"), "regaliceratops");
	public static ModelLayerLocation REGALICERATOPS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "regaliceratops_frame"), "regaliceratops_frame");
	public static ModelLayerLocation HUAXIAZHOULONG = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "huaxiazhoulong"), "huaxiazhoulong");
	public static ModelLayerLocation HUAXIAZHOULONG_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "huaxiazhoulong_frame"), "huaxiazhoulong_frame");
	public static ModelLayerLocation VELOCIRAPTOR = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "velociraptor"), "velociraptor");
	public static ModelLayerLocation VELOCIRAPTOR_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "velociraptor_frame"), "velociraptor_frame");
	public static ModelLayerLocation KUBANOCHOERUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "kubanochoerus"), "kubanochoerus");
	public static ModelLayerLocation KUBANOCHOERUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "kubanochoerus_frame"), "kubanochoerus_frame");
	public static ModelLayerLocation DECENNATHERIUM = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "decennatherium"), "decennatherium");
	public static ModelLayerLocation DECENNATHERIUM_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "decennatherium_frame"), "decennatherium_frame");
	public static ModelLayerLocation UTAHRAPTOR = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "utahraptor"), "utahraptor");
	public static ModelLayerLocation UTAHRAPTOR_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "utahraptor_frame"), "utahraptor_frame");
	public static ModelLayerLocation SHONISAURUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "shonisaurus"), "shonisaurus");
	public static ModelLayerLocation SHONISAURUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "shonisaurus_frame"), "shonisaurus_frame");
	public static ModelLayerLocation APATOSAURUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "apatosaurus"), "apatosaurus");
	public static ModelLayerLocation APATOSAURUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "apatosaurus_frame"), "apatosaurus_frame");
	public static ModelLayerLocation BRACHIOSAURUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "brachiosaurus"), "brachiosaurus");
	public static ModelLayerLocation BRACHIOSAURUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "brachiosaurus_frame"), "brachiosaurus_frame");
	public static ModelLayerLocation IGUANODON = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "iguanodon"), "iguanodon");
	public static ModelLayerLocation IGUANODON_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "iguanodon_frame"), "iguanodon_frame");
	public static ModelLayerLocation AMARGASAURUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "amargasaurus"), "amargasaurus");
	public static ModelLayerLocation AMARGASAURUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "amargasaurus_frame"), "amargasaurus_frame");
	public static ModelLayerLocation NIGERSAURUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "nigersaurus"), "nigersaurus");
	public static ModelLayerLocation NIGERSAURUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "nigersaurus_frame"), "nigersaurus_frame");
	public static ModelLayerLocation SARCOSUCHUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "sarcosuchus"), "sarcosuchus");
	public static ModelLayerLocation SARCOSUCHUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "sarcosuchus_frame"), "sarcosuchus_frame");
	public static ModelLayerLocation PLIOSAURUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "pliosaurus"), "pliosaurus");
	public static ModelLayerLocation PLIOSAURUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "pliosaurus_frame"), "pliosaurus_frame");
	public static ModelLayerLocation HATZEGOPTERYX = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "hatzegopteryx"), "hatzegopteryx");
	public static ModelLayerLocation HATZEGOPTERYX_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "hatzegopteryx_frame"), "hatzegopteryx_frame");
	public static ModelLayerLocation CARCHARODONTOSAURUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "carcharodontosaurus"), "carcharodontosaurus");
	public static ModelLayerLocation CARCHARODONTOSAURUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "carcharodontosaurus_frame"), "carcharodontosaurus_frame");
	public static ModelLayerLocation EDMONTOSAURUSANNECTENS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "edmontosaurusannectens"), "edmontosaurusannectens");
	public static ModelLayerLocation EDMONTOSAURUSANNECTENS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "edmontosaurusannectens_frame"), "edmontosaurusannectens_frame");
	public static ModelLayerLocation TYRANNOSAURUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "tyrannosaurus"), "tyrannosaurus");
	public static ModelLayerLocation TYRANNOSAURUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "tyrannosaurus_frame"), "tyrannosaurus_frame");
	public static ModelLayerLocation SPINOSAURUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "spinosaurus"), "spinosaurus");
	public static ModelLayerLocation SPINOSAURUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "spinosaurus_frame"), "spinosaurus_frame");
	public static ModelLayerLocation MEGACEROPS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "megacerops"), "megacerops");
	public static ModelLayerLocation MEGACEROPS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "megacerops_frame"), "megacerops_frame");
	public static ModelLayerLocation EREMOTHERIUM = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "eremotherium"), "eremotherium");
	public static ModelLayerLocation EREMOTHERIUM_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "eremotherium_frame"), "eremotherium_frame");
	public static ModelLayerLocation PANTHERATIGRIS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "pantheratigris"), "pantheratigris");
	public static ModelLayerLocation PANTHERATIGRIS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "pantheratigris_frame"), "pantheratigris_frame");
	public static ModelLayerLocation COTYLORHYNCHUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "cotylorhynchus"), "cotylorhynchus");
	public static ModelLayerLocation COTYLORHYNCHUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "cotylorhynchus_frame"), "cotylorhynchus_frame");
	public static ModelLayerLocation ALLOSAURUS = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "allosaurus"), "allosaurus");
	public static ModelLayerLocation ALLOSAURUS_FRAME = new ModelLayerLocation(new ResourceLocation(FossilMod.MOD_ID, "allosaurus_frame"), "allosaurus_frame");

	@SubscribeEvent
	public static void registerLayerDefinition(EntityRenderersEvent.RegisterLayerDefinitions event) {
		event.registerLayerDefinition(TROPAEUM, TropaeumFossilSlabModel::createBodyLayer);
		event.registerLayerDefinition(ALIENUM, AlienumFossilSlabModel::createBodyLayer);
		event.registerLayerDefinition(EUNOTOSAURUS, EunotosaurusFossilModel::createBodyLayer);
		event.registerLayerDefinition(EUNOTOSAURUS_FRAME, EunotosaurusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(PELECANIMIMUS, PelecanimimusFossilModel::createBodyLayer);
		event.registerLayerDefinition(PELECANIMIMUS_FRAME, PelecanimimusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(STENOKRANIO, StenokranioFossilModel::createBodyLayer);
		event.registerLayerDefinition(STENOKRANIO_FRAME, StenokranioFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(HENODUS, HenodusFossilModel::createBodyLayer);
		event.registerLayerDefinition(HENODUS_FRAME, HenodusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(ACANTHOSTEGA, AcanthostegaFossilModel::createBodyLayer);
		event.registerLayerDefinition(ACANTHOSTEGA_FRAME, AcanthostegaFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(PROTOCERAS, ProtocerasFossilModel::createBodyLayer);
		event.registerLayerDefinition(PROTOCERAS_FRAME, ProtocerasFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(DIPLOCAULUSMAGNICORNIS, DiplocaulusmagnicornisFossilModel::createBodyLayer);
		event.registerLayerDefinition(DIPLOCAULUSMAGNICORNIS_FRAME, DiplocaulusmagnicornisFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(TIKTAALIK, TiktaalikFossilModel::createBodyLayer);
		event.registerLayerDefinition(TIKTAALIK_FRAME, TiktaalikFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(SUMINIA, SuminiaFossilModel::createBodyLayer);
		event.registerLayerDefinition(SUMINIA_FRAME, SuminiaFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(MEGALANCOSAURUS, MegalancosaurusFossilModel::createBodyLayer);
		event.registerLayerDefinition(MEGALANCOSAURUS_FRAME, MegalancosaurusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(RIOJASUCHUS, RiojasuchusFossilModel::createBodyLayer);
		event.registerLayerDefinition(RIOJASUCHUS_FRAME, RiojasuchusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(DREPANOSAURUS, DrepanosaurusFossilModel::createBodyLayer);
		event.registerLayerDefinition(DREPANOSAURUS_FRAME, DrepanosaurusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(MANIDENS, ManidensFossilModel::createBodyLayer);
		event.registerLayerDefinition(MANIDENS_FRAME, ManidensFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(DASYCEPS, DasycepsFossilModel::createBodyLayer);
		event.registerLayerDefinition(DASYCEPS_FRAME, DasycepsFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(AQUILOPS, AquilopsFossilModel::createBodyLayer);
		event.registerLayerDefinition(AQUILOPS_FRAME, AquilopsFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(BANNYKUS, BannykusFossilModel::createBodyLayer);
		event.registerLayerDefinition(BANNYKUS_FRAME, BannykusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(YUANYANGLONG, YuanyanglongFossilModel::createBodyLayer);
		event.registerLayerDefinition(YUANYANGLONG_FRAME, YuanyanglongFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(MEI, MeiFossilModel::createBodyLayer);
		event.registerLayerDefinition(MEI_FRAME, MeiFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(ANATOSUCHUS, AnatosuchusFossilModel::createBodyLayer);
		event.registerLayerDefinition(ANATOSUCHUS_FRAME, AnatosuchusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(NQWEBASAURUS, NqwebasaurusFossilModel::createBodyLayer);
		event.registerLayerDefinition(NQWEBASAURUS_FRAME, NqwebasaurusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(SHUVUUIA, ShuvuuiaFossilModel::createBodyLayer);
		event.registerLayerDefinition(SHUVUUIA_FRAME, ShuvuuiaFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(SILESAURUS, SilesaurusFossilModel::createBodyLayer);
		event.registerLayerDefinition(SILESAURUS_FRAME, SilesaurusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(KENTROSAURUS, KentrosaurusFossilModel::createBodyLayer);
		event.registerLayerDefinition(KENTROSAURUS_FRAME, KentrosaurusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(PIATNITZKYSAURUS, PiatnitzkysaurusFossilModel::createBodyLayer);
		event.registerLayerDefinition(PIATNITZKYSAURUS_FRAME, PiatnitzkysaurusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(DEARC, DearcFossilModel::createBodyLayer);
		event.registerLayerDefinition(DEARC_FRAME, DearcFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(NASUTOCERATOPS, NasutoceratopsFossilModel::createBodyLayer);
		event.registerLayerDefinition(NASUTOCERATOPS_FRAME, NasutoceratopsFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(SYNTHETOCERAS, SynthetocerasFossilModel::createBodyLayer);
		event.registerLayerDefinition(SYNTHETOCERAS_FRAME, SynthetocerasFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(DIMETRODONGRANDIS, DimetrodonFossilModel::createBodyLayer);
		event.registerLayerDefinition(DIMETRODONGRANDIS_FRAME, DimetrodonFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(TUPANDACTYLUSNAVIGANS, TupandactylusnavigansFossilModel::createBodyLayer);
		event.registerLayerDefinition(TUPANDACTYLUSNAVIGANS_FRAME, TupandactylusnavigansFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(SKORPIOVENATOR, SkorpiovenatorFossilModel::createBodyLayer);
		event.registerLayerDefinition(SKORPIOVENATOR_FRAME, SkorpiovenatorFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(PROTOCERATOPSANDREWSI, ProtoceratopsandrewsiFossilModel::createBodyLayer);
		event.registerLayerDefinition(PROTOCERATOPSANDREWSI_FRAME, ProtoceratopsandrewsiFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(STRUTHIOMIMUS, StruthiomimusFossilModel::createBodyLayer);
		event.registerLayerDefinition(STRUTHIOMIMUS_FRAME, StruthiomimusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(MONTANOCERATOPS, MontanoceratopsFossilModel::createBodyLayer);
		event.registerLayerDefinition(MONTANOCERATOPS_FRAME, MontanoceratopsFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(DORUDON, DorudonFossilModel::createBodyLayer);
		event.registerLayerDefinition(DORUDON_FRAME, DorudonFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(GASTORNIS, GastornisFossilModel::createBodyLayer);
		event.registerLayerDefinition(GASTORNIS_FRAME, GastornisFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(KUTCHICETUS, KutchicetusFossilModel::createBodyLayer);
		event.registerLayerDefinition(KUTCHICETUS_FRAME, KutchicetusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(PRODINOCERAS, ProdinocerasFossilModel::createBodyLayer);
		event.registerLayerDefinition(PRODINOCERAS_FRAME, ProdinocerasFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(THYLACOLEO, ThylacoleoFossilModel::createBodyLayer);
		event.registerLayerDefinition(THYLACOLEO_FRAME, ThylacoleoFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(SINCLAIROMERYX, SinclairomeryxFossilModel::createBodyLayer);
		event.registerLayerDefinition(SINCLAIROMERYX_FRAME, SinclairomeryxFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(DINOCROCUTA, DinocrocutaFossilModel::createBodyLayer);
		event.registerLayerDefinition(DINOCROCUTA_FRAME, DinocrocutaFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(COELOPHYSIS, CoelophysisFossilModel::createBodyLayer);
		event.registerLayerDefinition(COELOPHYSIS_FRAME, CoelophysisFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(PLACERIAS, PlaceriasFossilModel::createBodyLayer);
		event.registerLayerDefinition(PLACERIAS_FRAME, PlaceriasFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(ENDOTHIODONBATHYSTOMA, EndothiodonbathystomaFossilModel::createBodyLayer);
		event.registerLayerDefinition(ENDOTHIODONBATHYSTOMA_FRAME, EndothiodonbathystomaFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(NIGERPETON, NigerpetonFossilModel::createBodyLayer);
		event.registerLayerDefinition(NIGERPETON_FRAME, NigerpetonFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(ARIZONASAURUS, ArizonasaurusFossilModel::createBodyLayer);
		event.registerLayerDefinition(ARIZONASAURUS_FRAME, ArizonasaurusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(POPOSAURUS, PoposaurusFossilModel::createBodyLayer);
		event.registerLayerDefinition(POPOSAURUS_FRAME, PoposaurusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(STAHLECKERIA, StahleckeriaFossilModel::createBodyLayer);
		event.registerLayerDefinition(STAHLECKERIA_FRAME, StahleckeriaFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(STAGONOLEPIS, StagonolepisFossilModel::createBodyLayer);
		event.registerLayerDefinition(STAGONOLEPIS_FRAME, StagonolepisFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(GUANLONG, GuanlongFossilModel::createBodyLayer);
		event.registerLayerDefinition(GUANLONG_FRAME, GuanlongFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(ICHTHYOSAURUS, IchthyosaurusFossilModel::createBodyLayer);
		event.registerLayerDefinition(ICHTHYOSAURUS_FRAME, IchthyosaurusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(SCELIDOSAURUS, ScelidosaurusFossilModel::createBodyLayer);
		event.registerLayerDefinition(SCELIDOSAURUS_FRAME, ScelidosaurusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(WUERHOSAURUS, WuerhosaurusFossilModel::createBodyLayer);
		event.registerLayerDefinition(WUERHOSAURUS_FRAME, WuerhosaurusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(BISONLATIFRONS, BisonlatifronsFossilModel::createBodyLayer);
		event.registerLayerDefinition(BISONLATIFRONS_FRAME, BisonlatifronsFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(SMILOSUCHUS, SmilosuchusFossilModel::createBodyLayer);
		event.registerLayerDefinition(SMILOSUCHUS_FRAME, SmilosuchusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(CRYOLOPHOSAURUS, CryolophosaurusFossilModel::createBodyLayer);
		event.registerLayerDefinition(CRYOLOPHOSAURUS_FRAME, CryolophosaurusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(DILOPHOSAURUS, DilophosaurusFossilModel::createBodyLayer);
		event.registerLayerDefinition(DILOPHOSAURUS_FRAME, DilophosaurusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(CERATOSAURUSDENTISULCATUS, CeratosaurusdentisulcatusFossilModel::createBodyLayer);
		event.registerLayerDefinition(CERATOSAURUSDENTISULCATUS_FRAME, CeratosaurusdentisulcatusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(YINGSHANOSAURUS, YingshanosaurusFossilModel::createBodyLayer);
		event.registerLayerDefinition(YINGSHANOSAURUS_FRAME, YingshanosaurusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(PATAGOSAURUS, PatagosaurusFossilModel::createBodyLayer);
		event.registerLayerDefinition(PATAGOSAURUS_FRAME, PatagosaurusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(EOABELISAURUS, EoabelisaurusFossilModel::createBodyLayer);
		event.registerLayerDefinition(EOABELISAURUS_FRAME, EoabelisaurusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(CAMPTOSAURUS, CamptosaurusFossilModel::createBodyLayer);
		event.registerLayerDefinition(CAMPTOSAURUS_FRAME, CamptosaurusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(KOOLASUCHUS, KoolasuchusFossilModel::createBodyLayer);
		event.registerLayerDefinition(KOOLASUCHUS_FRAME, KoolasuchusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(SAUROPELTA, SauropeltaFossilModel::createBodyLayer);
		event.registerLayerDefinition(SAUROPELTA_FRAME, SauropeltaFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(ABYSSOSAURUS, AbyssosaurusFossilModel::createBodyLayer);
		event.registerLayerDefinition(ABYSSOSAURUS_FRAME, AbyssosaurusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(MUTTABURRASAURUS, MuttaburrasaurusFossilModel::createBodyLayer);
		event.registerLayerDefinition(MUTTABURRASAURUS_FRAME, MuttaburrasaurusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(DEINONYCHUS, DeinonychusFossilModel::createBodyLayer);
		event.registerLayerDefinition(DEINONYCHUS_FRAME, DeinonychusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(BRACHYTRACHELOPAN, BrachytrachelopanFossilModel::createBodyLayer);
		event.registerLayerDefinition(BRACHYTRACHELOPAN_FRAME, BrachytrachelopanFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(TETHYSHADROS, TethyshadrosFossilModel::createBodyLayer);
		event.registerLayerDefinition(TETHYSHADROS_FRAME, TethyshadrosFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(REGALICERATOPS, RegaliceratopsFossilModel::createBodyLayer);
		event.registerLayerDefinition(REGALICERATOPS_FRAME, RegaliceratopsFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(HUAXIAZHOULONG, HuaxiazhoulongFossilModel::createBodyLayer);
		event.registerLayerDefinition(HUAXIAZHOULONG_FRAME, HuaxiazhoulongFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(VELOCIRAPTOR, VelociraptorFossilModel::createBodyLayer);
		event.registerLayerDefinition(VELOCIRAPTOR_FRAME, VelociraptorFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(KUBANOCHOERUS, KubanochoerusFossilModel::createBodyLayer);
		event.registerLayerDefinition(KUBANOCHOERUS_FRAME, KubanochoerusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(DECENNATHERIUM, DecennatheriumFossilModel::createBodyLayer);
		event.registerLayerDefinition(DECENNATHERIUM_FRAME, DecennatheriumFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(UTAHRAPTOR, UtahraptorFossilModel::createBodyLayer);
		event.registerLayerDefinition(UTAHRAPTOR_FRAME, UtahraptorFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(SHONISAURUS, ShonisaurusFossilModel::createBodyLayer);
		event.registerLayerDefinition(SHONISAURUS_FRAME, ShonisaurusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(APATOSAURUS, ApatosaurusFossilModel::createBodyLayer);
		event.registerLayerDefinition(APATOSAURUS_FRAME, ApatosaurusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(BRACHIOSAURUS, BrachiosaurusFossilModel::createBodyLayer);
		event.registerLayerDefinition(BRACHIOSAURUS_FRAME, BrachiosaurusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(IGUANODON, IguanodonFossilModel::createBodyLayer);
		event.registerLayerDefinition(IGUANODON_FRAME, IguanodonFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(AMARGASAURUS, AmargasaurusFossilModel::createBodyLayer);
		event.registerLayerDefinition(AMARGASAURUS_FRAME, AmargasaurusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(NIGERSAURUS, NigersaurusFossilModel::createBodyLayer);
		event.registerLayerDefinition(NIGERSAURUS_FRAME, NigersaurusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(SARCOSUCHUS, SarcosuchusFossilModel::createBodyLayer);
		event.registerLayerDefinition(SARCOSUCHUS_FRAME, SarcosuchusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(PLIOSAURUS, PliosaurusFossilModel::createBodyLayer);
		event.registerLayerDefinition(PLIOSAURUS_FRAME, PliosaurusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(HATZEGOPTERYX, HatzegopteryxFossilModel::createBodyLayer);
		event.registerLayerDefinition(HATZEGOPTERYX_FRAME, HatzegopteryxFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(CARCHARODONTOSAURUS, CarcharodontosaurusFossilModel::createBodyLayer);
		event.registerLayerDefinition(CARCHARODONTOSAURUS_FRAME, CarcharodontosaurusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(EDMONTOSAURUSANNECTENS, EdmontosaurusannectensFossilModel::createBodyLayer);
		event.registerLayerDefinition(EDMONTOSAURUSANNECTENS_FRAME, EdmontosaurusannectensFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(TYRANNOSAURUS, TyrannosaurusFossilModel::createBodyLayer);
		event.registerLayerDefinition(TYRANNOSAURUS_FRAME, TyrannosaurusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(SPINOSAURUS, SpinosaurusFossilModel::createBodyLayer);
		event.registerLayerDefinition(SPINOSAURUS_FRAME, SpinosaurusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(MEGACEROPS, MegaceropsFossilModel::createBodyLayer);
		event.registerLayerDefinition(MEGACEROPS_FRAME, MegaceropsFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(EREMOTHERIUM, EremotheriumFossilModel::createBodyLayer);
		event.registerLayerDefinition(EREMOTHERIUM_FRAME, EremotheriumFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(PANTHERATIGRIS, PantheratigrisFossilModel::createBodyLayer);
		event.registerLayerDefinition(PANTHERATIGRIS_FRAME, PantheratigrisFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(COTYLORHYNCHUS, CotylorhynchusFossilModel::createBodyLayer);
		event.registerLayerDefinition(COTYLORHYNCHUS_FRAME, CotylorhynchusFossilFrameModel::createBodyLayer);
		event.registerLayerDefinition(ALLOSAURUS, AllosaurusFossilModel::createBodyLayer);
		event.registerLayerDefinition(ALLOSAURUS_FRAME, AllosaurusFossilFrameModel::createBodyLayer);
	}
	
	@SubscribeEvent
	public static void init(final FMLClientSetupEvent event) {
		ClientProxy.setupBlockRenders();
	}
	
}
